### ISSUE TITLE
Container method should let the container connect to the host (e.g., for a debugger)

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#1022]
Many (most?) debugger setups expect the debugger to connect to the running process, for example as described in the [Local development with Java tutorial](https://www.telepresence.io/tutorials/java). However, there are few that want things to go the other way around, i.e. the process wants to connect to the debugger. Examples include [the PyCharm remote debug server](https://www.jetbrains.com/help/pycharm/remote-debugging-with-product.html#remote-debug-config) and the [DBG PHP debugger](http://www.php-debugger.com/dbg/faq.php##2). For these cases, it would be useful to let the user specify one or more ports to forward to the host machine.

Options

- Include an `/etc/hosts` entry for host.docker.internal that points to a routable address that actually reaches the host (name already set up on Docker for Mac) — need to tweak the `sshuttle` command to allow this
- Offer an option to forward specific localhost ports to the host machine, which Tel can do using `ssh` port forwarding as always

**Comment by BadgerOps** [comment]
Hi @ark3  I'm commenting here instead of #1065 although I'm experiencing the exact same scenario, wanting to use xdebug with telepresence. (Specifically `--new-deployment` or `--swap-deployment` with the `--docker-run` flag)

I'm pretty comfortable working in Python, but am having a bit of a rough time figuring out exactly how the sshuttle command is getting built in the proxy container. I'm happy to help work on this issue though if someone has time to help me get my head wrapped around it!

Cheers, Sol

**Comment by tenitski** [comment]
Are there any workarounds we can use in the meantime? Eg when using docker method add additional networks to a container?

**Comment by ark3** [comment]
Fixed in #1132
