### ISSUE TITLE
Any plans to support Istio / Knative deployments

### ISSUE THREAD

**Issue by JCzz** [telepresenceio/telepresence#1029]
Telepresence is so cool and it works perfect for normal k8s deployments - do you have any plans on supporting Istio / Knative?

**Comment by ark3** [comment]
As far as I know, Telepresence works okay with Istio right now. What would it mean to support Knative? Can you sketch out an example?

**Comment by JCzz** [comment]
Hi

In Knative they use a header for routing:
   `grpc.WithAuthority("")`
This routing is hitting a deployment name.

I think it would be awesome, to support this.

Thanks

**Comment by lisamburns** [comment]
I ran into issues attempting to use telepresence with knative as well. I tried to `telepresence --swap-deployment` with a deployment that had been created by knative. First, the new pod that was created was failing with this error message on the queue-proxy sidecar (sidecar is created by knative):

```
"admin server failed to listen: listen tcp :8022: bind: address already in use","stacktrace":"main.main\n\tknative.dev/serving/cmd/queue/main.go:229\nruntime.main\n\truntime/proc.go:203"}
```

I looked at port 8022 and there's some hard-coding in both knative and telepresence, neither is configurable, that may be the issue:
https://github.com/telepresenceio/telepresence/blob/9d2096a3ce094bb75d91e3ec1c8db80b3012e328/telepresence/connect/connect.py#L53-L58
https://github.com/knative/serving/blob/d91b5d6cdd290075a0a911ee97a5238ea19fdecb/pkg/networking/constants.go#L29-L31

The second issue that I ran into was that a second healthy pod spun up immediately (with both my workload and the queue-proxy sidecar), but it did not have the `datawire/telepresence` image swapped in.  One hypothesis here is that knative creates this new pod as part of its reconciliation loop after the swap.

**Comment by thallgren** [comment]
@JCzz are you seeing issues with Istio or Knative? If you do, please elaborate. If not, please close this ticket again.

**Comment by dsyer** [comment]
It's definitely not usable with Knative. I'm using Telepresence2 so the commands are different from the examples in @lisamburns comment, but the experience is similar. I can't get `telepresense intercept` to run at all even - it fails to detect the interceptable ports and won't take any hints I provide. The problem is to do with the way Knative generates and reconciles the deployment manifest, as she suggested I'm sure (but I'm not an expert so I can't explain how that works).

**Comment by sbaier1** [comment]
FWIW since i also ran into this issue (the root cause is that knative serving will override the deployment object edits from telepresence, so it's more of a knative issue, i suspect that supporting ksvc objects in telepresence is just too much to ask and also implies incompatibility with lots of other similar controllers, IMHO it would be more appropriate to just have a reconciliation pause in ksvc objects in knative-serving but that also comes with its own UX downsides)

It is generally possible by specifying these annotations on the ksvc object:

```yaml
spec:
  template:
    metadata:
      annotations:
        telepresence.getambassador.io/inject-container-ports: "50051"
        telepresence.getambassador.io/inject-traffic-agent: enabled
```

this will inject the traffic-agent at all times of course. but intercepting by pointing to the current deployment object works as intended using this workaround.
