### ISSUE TITLE
Telepresence --run-shell doesn't keep aliases

### ISSUE THREAD

**Issue by ohemelaar** [telepresenceio/telepresence#1074]
The new shell spawned by telepresence doesn't source `.bashrc`/`.bash_profile` in order to load the user's custom shell configuration. I guess there's a good reason for this, but then is there a way to define a custom shell configuration for telepresence? Something like a `.telepresencerc` file?

I'm using version `0.101`.

**Comment by ark3** [comment]
The shell spawned by Telepresence is locked down to avoid issues with fancy shell prompts that use`kubectl` commands and other such things. This is mostly to protect users of the inject-tcp method. We should revisit how this works, especially since the default vpn-tcp method probably does not require that protection.

You can work around this by having Telepresence run your shell explicitly, (`--run bash` or whatever), in which case Telepresence will not modify your shell invocation at all.
