### ISSUE TITLE
Telepresence breaks networking for minikube --vm-driver none

### ISSUE THREAD

**Issue by dfrancolr** [telepresenceio/telepresence#1131]
I'm using telepresence version 101 with latest minikube (tried 1.3.1 and 1.4.0) on Linux (Ubuntu 18.04 or Mint 19.2), with `--vm-driver none` to deploy a stack of services for a webapp, this includes database, backend, frontend, etc

After everything is deployed and working, when I run telepresence (vpn-tcp) to this cluster, all communication inside minikube stop. This happens if I try replacing a deployment, or even just creating a new one. Once telepresence's process exits, all communication gets back to normal. Also, from my host computer, I can access the frontend running inside minikube, but this frontend can't access the backend, the backend can't access the database, and so forth

The same stack works on a Mac using docker for desktop

The command used  is `telepresence --namespace localdev --context minikube --swap-deployment frontend --run npm run dev`

**Comment by ark3** [comment]
That sounds like a DNS loop due to your local cluster. Telepresence is supposed to detect this situation automatically, especially given the context name ("minikube"), but right now those heuristics are far from perfect. Can you please try using the `--local-cluster` option on your command (new with version 0.102)?

**Comment by dfrancolr** [comment]
I just tried, using command `telepresence --swap-deployment api --namespace localdev --context minikube --local-cluster --logfile /tmp/telepresence.log --run npm run dev`

and had the same issue. Just to be clear, communication from the host to the cluster works, either to the swapped deployment or not.
The swapped deployment is the backend of my application, and on the frontend, I see `ECONNREFUSED 10.96.29.223:80`
this is the result of describing the `api` service:
```Name:                     api
Namespace:                localdev
Labels:                   service=api
Annotations:              kubectl.kubernetes.io/last-applied-configuration:
                            {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"service":"api"},"name":"api","namespace":"localdev"},"spec":{"...
Selector:                 service=api
Type:                     NodePort
IP:                       10.96.29.223
Port:                     <unset>  80/TCP
TargetPort:               3002/TCP
NodePort:                 <unset>  30742/TCP
Endpoints:                172.17.0.11:3002
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>```

and this is a gist with the logs for the period: https://gist.github.com/dfrancolr/2472c317a7ea64c9c99e22a3c973785d

**Comment by ark3** [comment]
Thinking about this some more, my initial reaction was wrong. This is not a DNS loop, so the `--local-cluster` flag won't help here. I notice now (but missed the first time around) that you are using `--vm-driver none` as part of your Minikube setup. I think `sshuttle` is able to interfere with cluster networking because of that. I am not aware of a direct solution to this.

Are you tied to using Minikube in that configuration? Can you use the normal VM-based Minikube, or [KinD](https://github.com/kubernetes-sigs/kind), or [k3d](https://github.com/rancher/k3d/), or something else instead?

**Comment by dfrancolr** [comment]
I'm not tied to it, but I had really bad I/O performance with `virtualbox` so tried it instead
Thanks for the suggestions, I'll try them and update here with what I find

**Comment by dfrancolr** [comment]
`k3d` worked, so the issue probably is related to running minikube with `--vm-driver none`
Once again, thanks for the help!

**Comment by ark3** [comment]
It would be great if we could detect this case and report an error.

**Comment by donnyyung** [comment]
I'm not sure if this is still an issue with telepresence 2, so adding the `exploration` and `v2` label.
