### ISSUE TITLE
telepresence command line fails with ImagePullBackoff when no access to public Docker Hub

### ISSUE THREAD

**Issue by ddifranc** [telepresenceio/telepresence#1193]
I'm trying to use telepresence in my company's internal kubernetes environment,
which only allows pulling images from an internal docker registry.
(Not the public Docker Hub).

telepresence command fails with:
RuntimeError: Pod isn't starting or can't be found: ....
{'message': 'Back-off pulling image "datawire/telepresence-k8s:0.103"', 'reason': 'ImagePullBackOff'}}}]

Is there a way to configure telepresence to use datawire/telepresence-k8s:0.103 from a different docker registry?

**Comment by ddifranc** [comment]
It appears this can be worked around by setting an environment variable:
TELEPRESENCE_REGISTRY

But i don't see that in the documentation.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2, since you can configure the registry here: https://www.telepresence.io/docs/latest/reference/config/

Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
