### ISSUE TITLE
[privacy] Support to turn off verbose k8s-proxy logging

### ISSUE THREAD

**Issue by KarolisL** [telepresenceio/telepresence#1226]
At least in VPN mode, k8s-proxy logs EVERY query executed from telepresence host machine. 
I see this as a **privacy breach**, since any cluster or logging system user can see which websites were accessed by a telepresence user while they were connected to telepresence.

Example of log messages:
```
2020-01-13T10:44:45+0000 [stdout#info] A query: b'github.com'
2020-01-13T10:44:45+0000 [stdout#info] Result for b'github.com' is ['140.82.118.3']
```

Ideally, such logs messages would be disabled by default, but it would be alright for us to have it as a CLI option (since we're using wrapper shellscript anyway).

**Comment by machine424** [comment]
@KarolisL, if you run Telepresence manually: (You have control on the `docker` image to be used in the `Telepresence`'s pod); As a simple workaround you can prevent `Twisted` (the framework that runs, catches `Telepresences`'s stdout and displays it as logs) from displaying its logs, you can do that by sending logs into `/dev/null` by replacing https://github.com/telepresenceio/telepresence/blob/master/k8s-proxy/run-priv.sh#L4 with `exec env PYTHONPATH=/usr/src/app twistd -l /dev/null--pidfile= -n -y ./forwarder.py` and rebuilding the docker image (`Dockerfile` is in the same folder), make sure that the docker image contains `/telepresence-` or `/telepresence-k8s` otherwise `Telepresence` will raise an error here: https://github.com/telepresenceio/telepresence/blob/master/telepresence/proxy/remote.py#L46.
To prevent `/dev/null` from being rotated if it receives SIGUSR1 you can use `exec env PYTHONPATH=/usr/src/app twistd -l=- --pidfile= -n -y ./forwarder.py 2>&1 >/dev/null` instead.
@ark3, Does `Telepresence`'s CLI need to control `Telepresence`'s output (in this case we need to do sth about `prints`'s, especially in https://github.com/telepresenceio/telepresence/blob/master/k8s-proxy/resolver.py or should we make `Twisted`'s logging customisable ?

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2, since our log levels are customizable https://www.telepresence.io/docs/latest/reference/config/#log-levels. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
