### ISSUE TITLE
Telepresence could be faster on localhost Kubernetes installation

### ISSUE THREAD

**Issue by iirekm** [telepresenceio/telepresence#1249]
`telepresence --method inject-tcp --run echo ok!  1,93s user 0,35s system 42% cpu 5,316 total`

Couldn't it run faster, at least when the Kubernetes is run locally (with k3s for example)?
Then most of the proxying machinery is probably not needed (all volumes and IPs are directly available locally), all is needed is telling DNS to use those IPs.

**Comment by ark3** [comment]
The biggest win is achieved by [using an existing deployment](https://www.telepresence.io/reference/connecting#running-telepresence-manually). You can turn off volume mounts with `--mount=false`.

**Comment by iirekm** [comment]
`telepresence --deployment telepresence` indeed improves speed, now it's twice as fast! Better but I think still there's huge area for improvement: those backgrount kubectl and ssh processes are probably not needed if k8s is on localhost.

`--mount=false` improves startup time in my case only a few milliseconds - not really important.

**Comment by ark3** [comment]
The `kubectl port forward` and `ssh` are used to establish connectivity to the cluster, in this case for `torsocks` so that inject-tcp can do its thing. If we can figure out how to avoid those (`kubectl port-forward` is particularly expensive) for local clusters, that could indeed be a big win. 

Can you suggest an approach? I know `k3s` lets you spin up a fake load balancer, which would be another way to get a connection into the cluster, but that takes even longer to start than `kubectl port-forward`.
