### ISSUE TITLE
Missing --expose in tutorial command

### ISSUE THREAD

**Issue by mvijftigschild** [telepresenceio/telepresence#1409]
When following: 
https://www.telepresence.io/tutorials/docker

We come to the part where we do a `swap-deployment`:
```
$ telepresence --swap-deployment hello-world --docker-run --rm -it -v $(pwd):/usr/src/app hello-dev
T: Volumes are rooted at $TELEPRESENCE_ROOT. See https://telepresence.io/howto/volumes.html for details.
T: Starting network proxy to cluster by swapping out Deployment hello-world with a proxy
T: Forwarding remote port 8000 to local port 8000.

T: Setup complete. Launching your container.
 * Serving Flask app "server" (lazy loading)
[...]
```
The output of the command shows the port forward, however the command is missing the `--expose` to make that happen.

The command should be:
```
$ telepresence --swap-deployment hello-world --expose 8000 --docker-run --rm -it -v $(pwd):/usr/src/app hello-dev
```

**Comment by ark3** [comment]
Thank you for the issue.

The tutorial _used to_ advise creating the original deployment using `kubectl run ... --expose ...`, which would include port information in the Deployment. Telepresence is able to discover this port information in the Deployment and expose the relevant ports automatically.

But then the Kubernetes folks decided that `kubectl run` would no longer create Deployments. We changed the tutorial to suggest `kubectl create ...` followed by `kubectl expose ...`. Unfortunately, this does not set up port information in the Deployment, which means the tutorial is now broken without the additional `--expose` you suggest.

The quick solution would be to add `--expose 8000` to the tutorial so that it works correctly once more. But this will not demonstrate Telepresence's automatic expose feature.

The best solution would be to have one set of manifests (Kubernetes YAML files) that all the tutorials can refer to and use via `kubectl apply`. We could even have a separate page that talks about the contents of the manifests and explains what's going on, although teaching Kubernetes is not really the goal here. Of course the Deployment manifest would include port information, allowing Telepresence to handle exposing ports automatically.
