### ISSUE TITLE
SSH port forward fails with return code 255, timeout on gethostbyname call

### ISSUE THREAD

**Issue by jaredgorski** [telepresenceio/telepresence#1419]
### What were you trying to do?

Swap a deployment on my local cluster with my local build

### What did you expect to happen?

My local build of the pod would be swapped with the pod on my cluster

### What happened instead?

Telepresence failed with this error:
```
Looks like there's a bug in our code. Sorry about that!

Background process (SSH port forward (exposed ports)) exited with return code 255. Command was:
  ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 55881 telepresence@127.0.0.1 -R '*:3001:127.0.0.1:3001'


Background process (SSH port forward (socks and proxy poll)) exited with return code 255. Command was:
  ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 55881 telepresence@127.0.0.1 -L127.0.0.1:55893:127.0.0.1:9050 -R9055:127.0.0.1:55894
```

This seems to be a similar problem (if not the same) to https://github.com/telepresenceio/telepresence/issues/1394. I opened this issue because there doesn't seem to be any valid workaround or progress on this issue. I've tried including `--method inject-tcp` but it seems to cause problems communicating with other pods in the local cluster. In need of a fix on this.

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--swap-deployment', 'console', '--local-cluster', '--logfile', '/Users/jaredgorski/Desktop/file.log', '--run', 'npm', 'run', 'dev']`
Version: `0.105`
Python version: `3.8.5 (default, Jul 21 2020, 10:42:08) 
[Clang 11.0.0 (clang-1100.0.33.17)]`
kubectl version: `(error: Command '['kubectl', 'version', '--short']' returned non-zero exit status 1.)`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin Jareds-MBP 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`

```
Background process (SSH port forward (exposed ports)) exited with return code 255. Command was:
  ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 55881 telepresence@127.0.0.1 -R '*:3001:127.0.0.1:3001'


Background process (SSH port forward (socks and proxy poll)) exited with return code 255. Command was:
  ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 55881 telepresence@127.0.0.1 -L127.0.0.1:55893:127.0.0.1:9050 -R9055:127.0.0.1:55894

```

Logs:

```
TEL | [81] exit 1 in 0.13 secs.
  31.3 TEL | [82] Capturing: python3 -c 'import socket; socket.gethostbyname("hellotelepresence-12.a.sanity.check.telepresence.io")'
  31.4  56 | c : DNS request from ('192.168.1.4', 61723) to None: 69 bytes
  31.9 TEL | [52] SSH port forward (exposed ports): exit 255
  31.9 TEL | [53] SSH port forward (socks and proxy poll): exit 255
  32.1  56 | c : DNS request from ('192.168.1.4', 56174) to None: 38 bytes
  32.3 TEL | [82] timed out after 1.01 secs.
  32.4  56 | c : DNS request from ('192.168.1.4', 56672) to None: 32 bytes
  32.4  56 | c : DNS request from ('192.168.1.4', 53099) to None: 37 bytes
  32.4  56 | c : DNS request from ('192.168.1.4', 60138) to None: 40 bytes
  32.5  56 | c : DNS request from ('192.168.1.4', 54697) to None: 55 bytes
  32.5  56 | c : DNS request from ('192.168.1.4', 60708) to None: 33 bytes
  33.5  56 | c : Accept TCP: 192.168.1.4:55919 -> 34.82.39.241:443.
  33.5  56 | c : Accept TCP: 192.168.1.4:55920 -> 34.82.39.241:443.

```

**Comment by parthshah-mt** [comment]
Version: 0.109
Mac OS Big Sur, Version 11.1

The above error just started coming in one evening, and is now persistent. 


`T: Background process (SSH port forward (socks and proxy poll)) exited with return code 255. Command was:
T:   ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5 -q -p 50050 telepresence@127.0.0.1 -L127.0.0.1:50065:127.0.0.1:9050 -R9055:127.0.0.1:50066


T: Proxy to Kubernetes exited. This is typically due to a lost connection.`


I'm sure that the internet connection is stable, and the same code has been working over a long period of time. The same is working from another similar device as well. 


Logs: 
`2021-02-14T20:09:28+0000 [stdout#info] A query: b'event-pipeline-rabbitmq'
  80.6  12 | 2021-02-14T20:09:28+0000 [stdout#info] AAAA query, sending back A instead: b'event-pipeline-rabbitmq'
  80.6  12 | 2021-02-14T20:09:28+0000 [stdout#info] A query: b'event-pipeline-rabbitmq'
  80.6  12 | 2021-02-14T20:09:28+0000 [stdout#info] Result for b'event-pipeline-rabbitmq' is ['172.20.111.18']
  80.7  12 | 2021-02-14T20:09:28+0000 [stdout#info] Result for b'event-pipeline-rabbitmq' is ['172.20.111.18']
  80.7  23 | c : Accept TCP: 192.168.29.146:50099 -> 172.20.111.18:5672.
  81.1  23 | c : DNS request from ('2405:201:11:b092:1580:1336:e386:6787', 59734, 0, 0) to None: 67 bytes
  81.1  23 | c : DNS request from ('2405:201:11:b092:1580:1336:e386:6787', 55796, 0, 0) to None: 67 bytes
  81.1  23 | c : DNS request from ('2405:201:11:b092:1580:1336:e386:6787', 56159, 0, 0) to None: 67 bytes
  82.1  23 | c : DNS request from ('2405:201:11:b092:1580:1336:e386:6787', 59734, 0, 0) to None: 67 bytes
  82.1  23 | c : DNS request from ('2405:201:11:b092:1580:1336:e386:6787', 55796, 0, 0) to None: 67 bytes
  82.1  23 | c : DNS request from ('2405:201:11:b092:1580:1336:e386:6787', 56159, 0, 0) to None: 67 bytes
  84.2  23 | c : DNS request from ('192.168.29.146', 54132) to None: 67 bytes
  84.2  23 | c : DNS request from ('192.168.29.146', 62757) to None: 67 bytes
  84.2  23 | c : DNS request from ('192.168.29.146', 64211) to None: 67 bytes
  85.2  23 | c : DNS request from ('192.168.29.146', 54132) to None: 67 bytes
  85.2  23 | c : DNS request from ('192.168.29.146', 62757) to None: 67 bytes
  85.2  23 | c : DNS request from ('192.168.29.146', 64211) to None: 67 bytes
  85.7  23 | client_loop: send disconnect: Broken pipe
  85.7  12 | error: read tcp 192.168.29.146:50061->3.0.30.242:443: read: software caused connection abort
  85.7  13 | E0215 01:39:33.480919    3581 portforward.go:233] lost connection to pod
  85.7 TEL | [16] SSH port forward (socks and proxy poll): exit 255
  85.7  23 | >> pfctl -a sshuttle6-12300 -F all
  85.7 TEL | [12] kubectl logs: exit 1
  85.7 TEL | Background process (kubectl logs) exited with return code 1. Command was:
  85.7 TEL |   kubectl --context arn:aws:eks:ap-southeast-1:191195949309:cluster/call-ai-dev --namespace dev logs -f telepresence-1613333287-8032541-3544 --container telepresence --tail=10
  85.7 TEL | 
  85.7 TEL | Recent output was:
  85.7 TEL |   2021-02-14T20:09:17+0000 [-] (UDP Port 63172 Closed)
  85.7 TEL |   2021-02-14T20:09:17+0000 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x7f2c9c3dba58>
  85.7 TEL |   2021-02-14T20:09:17+0000 [stdout#info] Result for b'4.sophosxl.net' is ['52.74.169.206', '52.77.5.31', '13.228.49.212', '18.139.130.166', '18.138.123.123', '18.139.175.0']
  85.7 TEL |   2021-02-14T20:09:17+0000 [stdout#info] Result for b'4.sophosxl.net' is ['52.77.5.31', '52.74.169.206', '13.228.49.212', '18.139.130.166', '18.138.123.123', '18.139.175.0']
  85.7 TEL |   2021-02-14T20:09:28+0000 [stdout#info] A query: b'event-pipeline-rabbitmq'
  85.7 TEL |   2021-02-14T20:09:28+0000 [stdout#info] AAAA query, sending back A instead: b'event-pipeline-rabbitmq'
  85.7 TEL | [13] kubectl port-forward: exit 0
  85.7 TEL |   2021-02-14T20:09:28+0000 [stdout#info] A query: b'event-pipeline-rabbitmq'
  85.7 TEL |   2021-02-14T20:09:28+0000 [stdout#info] Result for b'event-pipeline-rabbitmq' is ['172.20.111.18']
  85.7 TEL |   2021-02-14T20:09:28+0000 [stdout#info] Result for b'event-pipeline-rabbitmq' is ['172.20.111.18']
  85.7 TEL |   error: read tcp 192.168.29.146:50061->3.0.30.242:443: read: software caused connection abort
  85.7  23 | >> pfctl -X 3272713721807869721
  85.7  23 | >> pfctl -a sshuttle-12300 -F all
  85.7  23 | >> pfctl -X 3272713721807893881
  85.8  23 | c : fatal: server died with error code 255
  85.8 TEL | END SPAN runner.py:754(wait_for_exit)   15.6s
  85.8 >>> | 
  85.8 >>> | Background process (SSH port forward (socks and proxy poll)) exited with return code 255. Command was:
  85.8 >>> |   ssh -N -oServerAliveInterval=1 -oServerAliveCountMax=10 -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oConnectTimeout=5 -q -p 50050 telepresence@127.0.0.1 -L127.0.0.1:50065:127.0.0.1:9050 -R9055:127.0.0.1:50066
  85.8 >>> | 
  85.8 >>> | 
  85.8 >>> | Proxy to Kubernetes exited. This is typically due to a lost connection.
  85.8 >>> | 
  85.8 TEL | EXITING with status code 255
  85.8 >>> | Exit cleanup in progress
  85.8 TEL | (Cleanup) Terminate local process
  85.8 TEL | Killing local process...
  85.8 TEL | [23] sshuttle: exit 99`
