### ISSUE TITLE
Error when running telepresence in Macbook with M1 and bigsur

### ISSUE THREAD

**Issue by brunobevilaqua** [telepresenceio/telepresence#1556]
Issue when running `telepresence` in Macbook M1 running big sur. 
* I'm using Docker experimental version for M1. 
* 
```
Looks like there's a bug in our code. Sorry about that!

Traceback (most recent call last):
  File "/usr/local/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/local/bin/telepresence/telepresence/main.py", line 81, in main
    user_process = launch(
  File "/usr/local/bin/telepresence/telepresence/outbound/setup.py", line 157, in launch
    return run_docker_command(
  File "/usr/local/bin/telepresence/telepresence/outbound/container.py", line 195, in run_docker_command
    runner.check_call(
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 458, in check_call
    self._run_command_sync(
  File "/usr/local/bin/telepresence/telepresence/runner/runner.py", line 437, in _run_command_sync
    raise CalledProcessError(
subprocess.CalledProcessError: Command '['docker', 'run', '--network=container:telepresence-1615405153-925746-3968', '--rm', 'datawire/telepresence-local:0.109', 'wait']' returned non-zero exit status 1.


Here are the last few lines of the logfile (see /tmp/telepresence.log for the complete logs):

  35.7  40 |    7.2 >>> | Your process exited with return code 99.
  35.7  40 |    7.2 TEL | EXITING successful session.
  35.7  40 | T: Your process exited with return code 99.
  35.7  40 | [INFO  tini (1)] Main child exited normally (with status '99')
  35.7  48 | Connection to 127.0.0.1 closed by remote host.
  35.7 TEL | [48] Local SSH port forward: exit 255
  36.3 TEL | [40] Network container: exit 99
  40.7 TEL | (proxy checking local liveness)
  40.9  14 | 2021-03-10T19:39:28+0000 [Poll#info] Checkpoint
  60.8  49 | Failed to connect to proxy in remote cluster.
  60.9  49 | [INFO  tini (1)] Main child exited normally (with status '1')
  61.2 TEL | [49] exit 1 in 32.40 secs.
```

Full log attached.
[telepresence.log](https://github.com/telepresenceio/telepresence/files/6118435/telepresence.log)

**Comment by richardscarrott** [comment]
@brunobevilaqua did you ever find a solution to this?

**Comment by brunobevilaqua** [comment]
@richardscarrott I have, thanks Richard

**Comment by richardscarrott** [comment]
Hi @brunobevilaqua, could you share your solution, did you try telepresence v2?...we're using v1 and I was hoping it'd be possible to get it running on an M1 chip but I get the exact same error as you have in your attached logs.

**Comment by techiemac** [comment]
@brunobevilaqua, @richardscarrott, we are running into this exact issue and I suspect others are running into this. Like many, until telepresence supports multiple ports, we are stuck on V1.

When we find a solution, which is proving to be pretty elusive, we will post our findings. Unless either of you have additional info here.

**Comment by richardscarrott** [comment]
@techiemac we were able to move to telepresence 2 I'm afraid.

**Comment by techiemac** [comment]
Thanks for the response. 
We are pretty deep into the weeds at this point and our current working theory is that is has to do with the differences in how the docker hyperkit.framework hosted framework runs on M1 vs intel, especially with how the docker bridge network works. Right away we are noticing some differences that may hopefully prove to be a fruitful path.
Again, when we figure this out, we will post in here in case anyone else goes searching for this.

**Comment by techiemac** [comment]
Just an update to add more information (in case someone searches for this). Our config is running several docker containers:
* The container that contains the telepresence executable
* The telepresence-local container
* A services container that runs our code
We've narrowed it down to how the telepresence-local container communicates back to the container containing the executable. Our working theory is around how there is a lot of assumptions that any container calling `host.docker.internal` can get at another container's loopback (127.0.0.1) and this is critical for how those two container communicate. Based on how moby works on intel, it does appear to be possible to do this (something new learned every day), but the M1 docker host VM (both the one launched via qemu and the other one launched using the new experimental virtualization framework), do not have the same behavior.

I get the intent of this is to avoid exposing the port to the world and keeping everything within docker but I'm trying a couple of different approaches around modifying how the connectivity occurs between these containers (and will create a PR for the 1.0 stuff) once I figure out the best path while maintaining a secure mechanism here. Well, unless https://github.com/telepresenceio/telepresence/issues/1607 is completed before I get this fix out since we make heavy use of multiple port intercepts :).

I don't know if anyone from the telepresence team has any thoughts here but I'll keep plugging away at this.

**Comment by thallgren** [comment]
@techiemac I'm currently working on #1607. Don't have an estimate yet, but I would advise against spending time on a PR for the 1.0 stuff.
