### ISSUE TITLE
[v2] Feature Request -- show namespace in `telepresence list` output.

### ISSUE THREAD

**Issue by peteroneilljr** [telepresenceio/telepresence#1601]
Problem: When using mapped-namespaces or the namespace is inherited from the context, it is easy to lose track of what namespace you're looking at. This will serve as a gentle reminder of where you are.

Possible Output Examples
```
$ telepresence list
(showing deployments from default namespace)
verylargejavaservice : ready to intercept (traffic-agent not yet installed)
verylargedatastore   : ready to intercept (traffic-agent not yet installed)
dataprocessingservice: ready to intercept (traffic-agent already installed)
```

```
$ telepresence list -n apple
(showing deployments from apple namespace)
appleservice : ready to intercept (traffic-agent not yet installed)
```

**Comment by thallgren** [comment]
Looking at `kubectl get` I see that they don't report the namespace unless there are no resources found. When that happens, it prints "No resources found in xxx namespace". The `telepresence list` command simply states "No deployments". I think we should mimic `kubectl`'s behaviour when nothing is found.

Using mapped-namespaces will not change what namespace you're currently using, but it might block access to it and I can see the benefit in having the `list` command report "Namespace xxx is not currently mapped" instead of "No deployments".

The second example, where an extra line of output shows what the user just provided using `-n` doesn't seem very helpful. I'm not in favor of doing that.

I would like to avoid the extra line. If need be, perhaps we could show the namespace using a flag that enforces the same output format as the `-A` `--all-namespaces` option (all names are qualified), but I'm not sure how useful that would be.

@peteroneilljr would that address your concerns?

**Comment by peteroneilljr** [comment]
@thallgren sorry for the delay, but yes your suggestions will resolve this ticket!
