### ISSUE TITLE
[v2] Doesn't work inside of a Docker container

### ISSUE THREAD

**Issue by LukeShu** [telepresenceio/telepresence#1622]
There are many components to this, among them:
- https://github.com/telepresenceio/telepresence/issues/1618
- https://github.com/telepresenceio/telepresence/issues/1619
- https://github.com/telepresenceio/telepresence/issues/1620
- https://github.com/telepresenceio/telepresence/issues/1621

But also: Even if you work around all of those, there's an issue where something's going wrong in the daemon but I'm not sure what.  DNS is working, and the SOCKS proxy is working (tested via `curl --proxy socks5://localhost:1080 kubernetes`), but connections aren't getting sent to the SOCKS proxy.  I suspect that this issue will go away when @thallgren's TUN work lands.  But perhaps there's just another piece of the issue hiding behind this one.

**Comment by thallgren** [comment]
I have verified that when using my PR for the TUN-device, telepresence can run inside of a Docker container and perform intercepts and that remote volume mounts work OK. I used [this Dockerfile](/telepresenceio/telepresence/blob/thallgren/tp-in-docker/examples/tp-in-docker/Dockerfile) which I plan to include in a future PR.

**Comment by AntonBlomstrom** [comment]
I've been running Telepresence fine in a container. But only on rebuilds. If I leave the intercept active in the container when I exit vscode, then try to reopen the folder in the container again, I get this:

`telepresence: error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /tmp/telepresence-connector.socket: connect: connection refused"`

The command I'm running is this:

`"postAttachCommand": "telepresence intercept antblo-chat-frontend --namespace antblo-chat-frontend --port 5000 --env-file /intercept.env"`

I'll see if there's some way to automatically close the connection before the container is stopped, since keeping the container running appears to be the reason this shows up. If `telepresence quit` is run before the container is stopped, you will be able to open the connection back up next time without rebuilding the image.

**Comment by khussey** [comment]
This is fixed in the 2.3.0 release, which is now available.
