### ISSUE TITLE
[v2] Can't intercept workloads without Service

### ISSUE THREAD

**Issue by LukeShu** [telepresenceio/telepresence#1647]
Some workloads (such as controllers) don't respond to incoming traffic, but instead call out to other services to fetch their input.  These workloads likely don't have a `Service` associated with them; and even if they do, the `Service` likely doesn't declare a port.

Right now, the suggested workaround is to declare a bogus `Service` with a bogus port.  That's obviously sub-optimal.  We add the capability to intercept a workload without using a `Service` to hijack any ports.

This is probably a good opportunity to clean up some UX wonkiness with the arguments to `telepresence intercept`.

**Comment by maelvls** [comment]
~This limitation makes me stay on Telepresence v1~. As you mentioned, I wish we could skip having to create a service resource when developing Kubernetes controllers. I expand on my use-case in [Use-case: Telepresence 1 + mitmproxy for debugging cert-manager](https://github.com/maelvls/kubectl-incluster#use-case-telepresence-1--mitmproxy-for-debugging-cert-manager).

**Update 1 June 2023:** The command `telepresence connect` is actually enough when I don't need to expose any port on the controller.

**Update 2 Oct 2023:** A service is still required if I want to test an endpoint exposed by the controller pod but exposed via a Service. I found to be stuck in two situations: the `/healthz` endpoint and the `/metrics` endpoint. We don't create a Service for those two because (1) Kubernetes doesn't need a Service to do the health check, and (2) we use a PodMonitor for the metrics which doesn't require a Service either. My workaround is to create a temporary Service just so that telepresence v2 starts.
