### ISSUE TITLE
[v2] Wrong macFuse version checker

### ISSUE THREAD

**Issue by xavidop** [telepresenceio/telepresence#1651]
I see that you currently aure using these lines to check the macFuse version:
```go
	if bytes.Contains(out, []byte("OSXFUSE")) {
		return errors.New(`macFUSE 4.0.5 or higher is required on your local machine`)
	}
```
Actually I have macFuse 4.1.0 installed from osxfuse site and sshfs 2.5.0 installed from osxfuse site too:
macFuse:
![image](https://user-images.githubusercontent.com/4416096/114016786-7f52fd80-986b-11eb-8c4c-17fa7114af17.png)
sshfs -V output:
```bash
bash-3.2$ sshfs -V
SSHFS version 2.5 (OSXFUSE SSHFS 2.5.0)
FUSE library version: 2.9.9
fuse: no mount point
```
as you can see, the OSXFUSE string still appearing.

I am running telepresence v2.1.4 on macOS:
```console
telepresence version
Client v2.1.4 (api v3)
Daemon v2.1.4 (api v3)
```

can you take a look at it? Did I execute wrong any installation step?

Thank you,
Xavi

**Comment by a502270682** [comment]
same problem +1

**Comment by p4elkin** [comment]
Also having this problem, does anyone know a workaround? It seems like even today macFUSE comes with libfuse2 and => sshfs 2.5 is the only available option (based on [this](https://groups.google.com/g/osxfuse-group/c/O8I7NbVTmOk/m/nerWE1MEAwAJ)). 

I presume the maintainers must have managed to get it running themselves somehow? Are there any tips?

Thanks

**Comment by thallgren** [comment]
I install the latest stable of MacFUSE from here using the dmg installer: https://osxfuse.github.io/ (currently 4.1.2)

This is the subsequent output from `sshfs -V`:
```
➜  sshfs -V
SSHFS version 2.10
FUSE library version: 2.9.9
fuse: no mount point
```
It contains no mention of OSXFUSE.

**Comment by p4elkin** [comment]
@thallgren thanks for checking in! However, for me mere installation of MacFUSE doesn't bring in sshfs (and the latest available link on the website leads to sshfs 2.5). Are you sure you haven't somehow built sshfs 2.10 manually?

**Comment by thallgren** [comment]
Not 100 sure, but I probably used brew when I installed sshfs.
```
➜  ~ brew list sshfs
/usr/local/Cellar/sshfs/2.10_2/bin/sshfs
/usr/local/Cellar/sshfs/2.10_2/share/man/man1/sshfs.1
```

**Comment by p4elkin** [comment]
Okay, looks like I was able to pin it down after all:
* brew no longer offers the 2.10 version (at least couldn't find it w/ search), the 3.x version it ships isn't compatible with macos
* I've built it from [sources](https://github.com/libfuse/sshfs) using the `sshfs-2.10` tag.
* You need autotools installed but otherwise the process was just about following what `./configure` tells you to do
* One amendment I had to do was a step 6 from [these](https://www.reddit.com/r/macapps/comments/lea865/how_to_install_sshfs_on_big_sur/gor45rg/) helpful instructions (although I am not on Big Sur): `sed 's/include <fuse\_darwin.h>/\/\/# include <fuse\_darwin.h>/g' sshfs.c > sshfs.c.new && mv sshfs.c.new sshfs.c
`

And voila 🤞:
```
sshfs -V

SSHFS version 2.10
FUSE library version: 2.9.9
fuse: no mount point
```

**Comment by thallgren** [comment]
Closing this in favor of #1654 since I think it's better if we collect all brew install of sshfs/macFUSE in one ticket.
