### ISSUE TITLE
telepresence connect failed

### ISSUE THREAD

**Issue by a502270682** [telepresenceio/telepresence#1664]
When i try to connect by telepresence, it shows me some error like this:

Launching Telepresence Daemon v2.1.5 (api v3)
Need root privileges to run "/usr/local/bin/telepresence daemon-foreground /Users/guofeiyang/Library/Logs/telepresence '' ''"
Password:
Connecting to traffic manager...
Disconnecting...done
Telepresence Daemon quitting...done
telepresence: error: services "traffic-manager" is forbidden: User "feiyang.guo" cannot get resource "services" in API group "" in the namespace "ambassador"

anyone know what's wrong with it.

**Comment by khussey** [comment]
@a502270682 I'm sorry you're running into problems. Try checking that you have the necessary permissions as outlined at https://www.getambassador.io/docs/telepresence/latest/reference/rbac/.

**Comment by sichapman** [comment]
I am getting a similar error. After a little more testing it seems like the logic is broken in some way.

When the ambassador namespace doesn't exist (or I don't have access to it), instead of trying to create it, it thinks it is available and tries to get the services list, which fails as above

When the ambassador namespace is there (and I do have access to it), it fails with user cannot create resource namespaces error  - technically accurate since I only granted get/list/watch to my user as per the RBAC page, but there should have been no need to create a namespace at all!

If I grant create namespace access to the user, the connect works. But it obviously creates no namespace since ambasador was already there - so should not have needed create permission in the first place.
