### ISSUE TITLE
[v2] intercept a service which have internal dependencies

### ISSUE THREAD

**Issue by Tetragramato** [telepresenceio/telepresence#1671]
Hello,

I have a question about intercepting a service with internal dependencies like a DB.

I have a service which can access to a mongoDB via the URI inside the cluster (with the service name), and when i intercept it and run locally the service with the right env file, i have some Exceptions due to Connection reset.

When i make a portforward of the Mongo service on my computer and make the changes on env file to point my Mongo config to localhost, everything is working fine 🤔 

Also, how can i do a `--also-proxy` without touching my cluster, like in V1 ? 

Thanks for your help ;) 👍

**Comment by thallgren** [comment]
Please see this section about [External Dependencies](https://www.getambassador.io/docs/telepresence/latest/howtos/outbound/#external-dependencies-formerly---also-proxy) for a good work-around until we implement `--also-proxy`.

**Comment by AdamNowaczyk** [comment]
@thallgren I have similar issue and cannot use External Dependencies, because my mongodb is running in the same cluster, however since it's replicaset it's using headless service. Looks like underlying resolution to pod dns is not handled by Telepresence (I'm using version 2). 
Any suggestions on how to make that scenario work?

**Comment by efunk** [comment]
Delivered in the Telepresence 2.3.1 GA release.
