### ISSUE TITLE
[v2] Integration with Istio

### ISSUE THREAD

**Issue by rytswd** [telepresenceio/telepresence#1705]
From the [v2 blog post](https://blog.getambassador.io/whats-new-in-telepresence-2-dbdff62b82d5), I could see how Telepresence tries to achieve fast development cycle by using proxy, just like Service Mesh. In fact, the traffic manager and traffic agent are very similar to Istio's control plane (istiod) and data plane (envoy proxy sidecar). If I'm not mistaken, Telepresence v2 sounds like it would conflict with Istio components - but I couldn't find any note about using Telepresence v2 with other Service Mesh technologies.

Although the fast development cycle provided by Telepresence sounds great, I am not confident if Telepresence / Traffic Manager can fully replace what Istio provides. Also, many Service Mesh solutions provide traffic routing with headers and other sophisticated traffic management, and each has specific configurations and designs behind it. Replacing the current Istio setup with other Service Mesh solution is going to be a massive undertake by itself, and thus, it would be great if Telepresence v2 can simply be added to the cluster with Istio running already.

I could work out with Telepresence v1 with a lot of Istio configurations to get the interception behaviour. If Telepresence v2 is going to be the main stream, it would be great if integrations with other tools are also kept as viable path.

**Comment by sneko** [comment]
Hi @rytswd ,

Did you manage Telepresence `v2` with Istio when mTLS communication is enabled? When doing some tests (like `curl -sSL -D - http://aaa.bbb/hello`) I directly get:
```
curl: (52) Empty reply from server
```

Having the team thoughts about Istio would be valuable (cc @khussey @thallgren @ark3 ). For now I think I will stick to the `v1` otherwise.

Thank you,

**Comment by thallgren** [comment]
Closing this because Telepresence has been proven to work just fine together with Istio. It's a misconseption that we're trying to do what Istio does. We don't have a conflict with an existing Istio installation.

**Comment by rytswd** [comment]
@sneko
I have to admit that I haven't had the time to experiment this actually - but the error you got is exactly the concern I had. Also, having multiple sidecars for traffic routing seems to be asking for more trouble.

@thallgren 
My apologies for not making my intention clear, but I was mainly asking to get some clarification on integration possibilities and potential conflicts with other Service Mesh solutions. It would be helpful to have a section in FAQ about how Telepresence contrasts with other Service Mesh solutions, and if there is any specific integration requirements.

With v1, it was easier to integrate with Istio, but it was much more involved in order to handle complex scenarios such as using Telepresence backed service only for some specific traffic. This was definitely not the best UX and required a lot of Istio configurations, but it was at least in line with other Istio configurations. With v2, if I'm understanding this correctly, it would require updating Istio setup to somehow allow Telepresence traffic patterns, and also require additional routing setup for Telepresence's traffic manager. If Telepresence can provide the Istio configurations directly, we shouldn't need an extra sidecar, and that would make all the cluster setup nice and clean. I understand this is easier said than done, but wanted to hear how Telepresence will look to work with other Service Mesh solutions in the future.

**Comment by thallgren** [comment]
@rytswd No, that's not right.

You shouldn't need to update anything with Istio in order to use TP2, except for the namespace configuration if you choose to install the traffic manager in a namespace that hasn't been configured already, and if Istio is blocking port, you'll need to allow the pods to contact the traffic-manager on port 8081. The clients (the workstations) must be able to do port-forwards to the traffic-manager using that same port.

All traffic will then flow through Istio the same way as before. Intercepted traffic flows through our gRPC tunnels, completely invisible to Istio.

So, either install the traffic-manager in an Istio managed namespace, or add an Istio config to the ns where you choose to install it. Allow traffic to it's 8081 port and you're all set.

**Comment by thallgren** [comment]
@rytswd our sidecar does not aspire to be a service mesh. It's redirecting intercepted traffic to/from workstations based on a set of rules that vary depending on who's intercepting. It provides the workstation with a correct environment and also sets up an sftp server in the pod so that the workstation can mount file-systems exposed by the intercepted container. It ensures that DNS resolution originates from the right pod (pods' may have custom DNS), and that outbound traffic from the workstation originates from the intercepted pod (basically so that Istio understands where connect attempts stem from). I'm pretty sure that we cannot accomplish that without a sidecar, or with Istio's sidecar for that matter.

**Comment by thallgren** [comment]
Also worth noting. Apart from what goes on in our gRPC, we don't route traffic outside the pod at all. We route using ports on localhost.

**Comment by rytswd** [comment]
@thallgren 
Thanks for the detailed info, those are great to know! Upon reading the blog post about v2 release and new architecture document, I originally got the impression that the v2 architecture was akin to Service Mesh solutions especially around intercepting traffic. With your explanations, I understand what role Telepresence sidecars play - SFTP server is certainly not a part of the picture for any Service Mesh AFAIK, and if the Telepresence's sidecar is only doing local routing, that's less likely to interfere with Istio sidecar. Perhaps all the details you shared here would be worth having a separate article for - something like https://www.getambassador.io/docs/telepresence/latest/reference/linkerd/, but for not just Linkerd but Service Mesh in general? 

I'm still unsure if all the Telepresence features will work smoothly, but I think I just need to experiment a bit more. I'll certainly give it a try in the coming weeks, and report if anything comes up ☺️

**Comment by thallgren** [comment]
Thanks. I agree that we need to provide more info on our architecture and how it works together with service meshes. I'll look into that.

**Comment by amh4r** [comment]
More documentation on service meshes would be very helpful. I haven't been able to get Telepresence to work with Consul Connect
