### ISSUE TITLE
V2: local only intercept

### ISSUE THREAD

**Issue by cyrus-mc** [telepresenceio/telepresence#1848]
I am not sure if this is an issue or a feature request. 

When creating an intercept there is the option `local-only` which reads as `Declare a local-only intercept for the purpose of getting direct outbound access to the intercept's namespace`.

I take that to mean that all outbound traffic is routed through the cluster but service communication for the intercepted service won't be routed back to your local system. Setting up a `local-only` intercept seems to validate my assumption. Route rules are setup for the cluster CIDR blocks (plus any additional specified by `also-proxy`). Request traffic to the specified intercepted service is handled by the intercepted POD directly.

However, connection origin, 

```
A request to connect to an IP-address that belongs to one of the subnets of the VIF will cause a connection request to be made in the cluster. As with host name lookups, the request will originate from the traffic-manager unless the client has ongoing intercepts. 
```

Does not seem to hold with `local-only` as connection origin seems to be the traffic manager. 

Our use case for `local-only` is to allow a local development environment in which a developers workstation/IDE/code can appear as if it is running from within the cluster (allow access to cluster resources, testing IAM role association, network policies, etc) while not affecting the functioning of the intercepted service (so traffic for that service is not routed to their local instance). 

I know this can accomplished with preview URLs (or selective intercepts) but I am looking for a simpler workflow for Developers in which they don't need to login to Ambassador cloud. Plus in this workflow the preview URLs aren't required as they would never be shared out.

**Comment by thallgren** [comment]
The `--local-only` is a way to establish DNS resolution for single label names, nothing else. If you declare a `--local-only` intercept to a namespace ("default" if no namespace), then you can access services in that namespace without qualifying them with a namespace name. E.g.e `hello` instead of `hello.default`. The option is intended to support the use case where a service is being developed but it has not yet been deployed.

**Comment by thallgren** [comment]
Regarding the "connection-origin": It is not possible for telepresence to make an outbound connection originate from a namespace unless a real (a non local) intercept is present in that namespace because there's no `traffic-agent` available that the connection can originate from. If you have that requirement, you must first deploy the pod that you intend to intercept or intercept some other pod in the same namespace.

**Comment by cyrus-mc** [comment]
Thanks for the clarification.
