### ISSUE TITLE
Please support alternate shells besides Bash (e.g. Fish, ZSH)

### ISSUE THREAD

**Issue by plombardi89** [telepresenceio/telepresence#191]
It would be nice if `telepresence` could automatically detect my shell and support fish and zsh.

**Comment by itamarst** [comment]
Note that when using `--mode inject` we need to disable configuration scripts (e.g. `.bashrc`) since they may e.g. run kubectl to setup autocompletion, and kubectl doesn't work under inject mode. We already do that for `bash`, would need to do so for other shells as well.

You can lookup user's shell using https://docs.python.org/3/library/pwd.html

**Comment by ark3** [comment]
`pwd.getpwuid(os.getuid()).pw_shell`

**Comment by ark3** [comment]
We should only do this for inject-tcp. A workaround is `telepresence --run bash` or whatever shell you want, but beware that stuff can go wrong in inject-tcp mode.

**Comment by thallgren** [comment]
This is no longer and issue in Telepresence v2. Just start whatever shell that is desired.
