### ISSUE TITLE
[v2] Not all env variables are set with intercept

### ISSUE THREAD

**Issue by ipleten** [telepresenceio/telepresence#1935]
I'm running tp intercept on deployment with multiple containers and seems not all environment variables are set.
I definitely see some missing variable set to one of containers. 

I think TP picks first container and copies env vars from it.
While it's possible to set annotation to [specify](https://kubernetes.io/docs/reference/labels-annotations-taints/#kubectl-kubernetes-io-default-container) default container, env vars from all containers probably should be merged  (which might cause problems if they are different for each container) 

$TELEPRESENCE_CONTAINER shows that TP picked wrong container.

**Comment by Schille** [comment]
We've faced the same troubles with missing _environment variables_ during an _intercept_ with _--docker-run_.
We're using an _oauth2 reverse proxy_ as sidecar for JWT validation and claim/header mapping, i.e. all traffic passes the sidecar before entering the application container.

![oauth2-sidecar](https://user-images.githubusercontent.com/676722/134465919-a93e2230-0096-4d3a-9119-b695ba0f04ee.png)

The intercept operation always picks up _only_ the environment variables of the sidecar ("ENVs B") which causes the local container to fail during startup (because of missing database connection parameter). That also happens when specifying the correct _servicePortIdentifier_ ("8080") as stated in the documentation: https://www.telepresence.io/docs/latest/reference/intercepts/#creating-an-intercept-when-a-service-has-multiple-ports

I suppose _Telepresence2_ always selects the container which is targeted at from the service to export the environment variables from. 
**Our workaround** for the time being is to add the env vars from the application ("ENVs A") to the sidecar in our Helm charts for certain environments (i.e. development, testing) to get the intercept with a local container running. The _proxy_ now holds all values for the application which is not ideal.

Is this currently a missing feature ("pull env from container x") or did we miss something from the documentation?

**Comment by cindymullins-dw** [comment]
In v[2.3.3](https://www.getambassador.io/docs/telepresence/latest/release-notes#2.3.3) we introduced the --to-pod flag that can be used to port-forward sidecars' ports from an intercepted pod.  Use this to, for example, access proxy/helper sidecars in the intercepted pod. The default protocol is TCP but we added UDP compatibility in [2.6.8](https://www.getambassador.io/docs/telepresence/latest/release-notes#2.6.8).

You could also make two intercepts on both containers.  One service exposes two different ports so you could make an intercept on each those just to get those env vars to the local machine.
