### ISSUE TITLE
Support installing/connecting to agent in DeploymentConfig workloads

### ISSUE THREAD

**Issue by sichapman** [telepresenceio/telepresence#1990]
As far as I can tell, Telepresence 2 combined with Openshift (4.7) seems to work fine with Deployments and StatefulSets but some of our pods are held in DeploymentConfigs, which do not appear in `telepresence list` as interceptable and `telepresence intercept` gives a not found error.

If I use the mutator webhook I can get the agent installed into the pod, but that still doesn't help connecting to it from the client side.

**Comment by edeandrea** [comment]
+1 to this.

**Comment by thallgren** [comment]
I'm closing this feature request because the [OpenShift DeploymentConfig has been deprecated](https://developers.redhat.com/learning/learn:openshift:replace-deprecated-deploymentconfigs-deployments/resource/resources:convert-deploymentconfig-deployment) and users are recommended to instead use a Deployment.
