### ISSUE TITLE
[label: friction] User requests clarification on Footnote about namespaces

### ISSUE THREAD

**Issue by cindymullins-dw** [telepresenceio/telepresence#2020]
DOCS-issue: In Telepresence Onboarding session of 8/26, Tomer Lev commented that their org relies on namespace set up.  They're concerned about this footnote and asked for clarification as to if/how namespaces will be supported and which features re namespaces would not be supported in future versions.

https://www.getambassador.io/docs/telepresence/latest/reference/routing/#footnotes

1: A future version of Telepresence will not allow concurrent intercepts that span multiple namespaces.

**Comment by thallgren** [comment]
That remark is still valid. The reason is that from a network standpoint, telepresence puts the workstation that performs an intercept "in a pod in the cluster". Outgoing traffic from the workstation must originate from that pod's namespace, or it will in many cases be blocked. If we allow that a workstation has multiple concurrent intercepts in more than one namespace, then there's no way to determine what namespace the workstation's outgoing traffic should originate from.

The remark should be rephrased to clarify that it applies to one single workstation.
