### ISSUE TITLE
VPN breaks telepresence

### ISSUE THREAD

**Issue by itamarst** [telepresenceio/telepresence#217]
See https://github.com/datawire/telepresence/issues/210#issuecomment-312868407

A priori I would expect starting a VPN *after* telepresence is started in `vpn-tcp` mode to break DNS.

**Comment by itamarst** [comment]
I think I will "fix" this by just noting limitations on startup, since there's a number of them.

**Comment by Reasno** [comment]
Is this a bug or a hard limitation? If it is a bug then it can be fixed right?

I asked because our Kubernetes cluster hides behind a VPN. So I can't use telepresence for now.

**Comment by DrongoX** [comment]
Hello @itamarst, we have an issue since we really need some VPN connections to organize a developer's local environment. So in order to use Telepresence we have to disconnect/reconnect VPNs each time. Is there either any advice to workaround it, either any vision if this limitation will be removed in future? Thanks

**Comment by ark3** [comment]
I suggest giving [the container method](https://www.telepresence.io/tutorials/docker) a try. It works well under a VPN, as does the inject-tcp method.

**Comment by DrongoX** [comment]
Hello @ark3 
Thank you! I appreciate your quick response.
Correct me if I'm wrong.
The container method require us to run the local project inside a Docker container... Well, unfortunately most of our code is in Java, so the local dev/debug workflow will require us to rebuild the project and docker image after each code change, which doesn't seem to be very productive.

Seems to me like we should then give inject-tcp a try...

**Comment by ark3** [comment]
The whole point of Telepresence is to avoid rebuilding the Docker image. You can do that because the container is running on your local machine. Please check out [this example](https://www.telepresence.io/tutorials/java). In short, we encourage you to build and run in the container. You can still use your IDE by volume mounting your source code into the container.

**Comment by DrongoX** [comment]
Thank a lot, I will look deeper in it. @ark3
