### ISSUE TITLE
Intercept sidecar calls 

### ISSUE THREAD

**Issue by alan994** [telepresenceio/telepresence#2215]
**Describe the bug**
I'm trying to connect telepresence with my app service running in the k8s pod. In the same pod, I have a sidecar (Dapr) that is communicating with my app on `localhost`. When I run `telepresence intercept` and call Dapr from my service running locally communication works because I ran `kubectl port-forward dapr-service`. So my local machine is seeing Dapr at `localhost`. But, when Dapr needs to call my application it calls it on `localhost` as well. It calls remote service, not my local service. 
I completely understand that `telepresence intercept` listens only for traffic going through the Kubernetes service that is pointing to my app container and it also requires a specific header (for the personal intercept), but I was hoping there is some way to make it work. 

I already asked the Dapr community is there any config I can set so Dapr could call my service by Kubernetes service, not by `localhost`, but there is not. 

![image](https://user-images.githubusercontent.com/8849512/142060201-a7a52310-6b2d-4630-8193-4288e92adc4e.png)

**To Reproduce**
1. Create sample service and Dapr sidecar 
2. Connect Telepresence to your service 
3. Push some message to queue so Dapr will need to call your application
4. You will not get this call redirected to your local service, instead, Dapr will call remote service 

**Expected behavior**
Call my local service

**Versions (please complete the following information):**
Client: v2.4.5 (API v3)
Root Daemon: not running
User Daemon: not running

Windows 10
Azure Kubernetes Service

**Comment by olitomlinson** [comment]
I would love to see telepresence support dapr sidecars fully too.

**Comment by thallgren** [comment]
Please try using `--replace` when intercepting. That should give the desired effect.

**Comment by olitomlinson** [comment]
@thallgren 

although the `-- replace` command here is helpful in replacing the remote service with a dummy service, **however** does this address point that OP was making?

OP said :

> But, when Dapr needs to call my application it calls it on localhost as well. It calls remote service, not my local service.

The problem here is Dapr (which is running in the pod) will be calling `localhost:xxxx` in order to reach the App container.

However, we do not want Dapr to call the remote service (via localhost:xxxx) it needs to call the **locally running App** (not the remote app in the pod)

Does that make sense?

**Comment by thallgren** [comment]
@olitomlinson yes, it makes sense. It means that the sidecar must listen to `localhost:xxxx` and then dispatch whatever comes into that port to  the locally running app. I believe that should work now (if the app is configured with that container port).

Without a replace, it can never work because there's no way for our sidecar to intercept a port on localhost that is already bound to another listener (the app container).
