### ISSUE TITLE
multi port support

### ISSUE THREAD

**Issue by mumayuan** [telepresenceio/telepresence#2318]
**Please describe your use case / problem.**
In our product, we have a major component that have more than one ports open (one websocket and one http), which opens more than one port through load balancer. In order to use telepresense to allow local debugging, I will need to proxy both ports.  Currently I did not find a way to achieve that. 

**Describe the solution you'd like**
Allow telepresence to intercept more than one port for the same service. 

**Describe alternatives you've considered**
Haven't come up with any alternative approaches yet.

**Versions (please complete the following information)**
  - Output of `telepresence version` (just in case the feature exists in future versions) : v2.4.10
  - Kubernetes Environment and Version:  k3s v1.20.6+k3s1

**Additional context**
We also have a use case with multiple containers running in the same pod.  If we can support intercept more than port as described above, it should also resolve this use case.

**Comment by macstevens-bread** [comment]
Hey @mumayuan, I'm not on the telepresence team but it looks like this is a dup of https://github.com/telepresenceio/telepresence/issues/1607.

Please upvote this because I know a ton of telepresence users are in the exact same situation and are still stuck on telepresence 1.0. So hopefully we can get multi port support soon.

**Comment by techiemac** [comment]
@mumayuan while I'm not on the telepresence team, this looks like a dup of https://github.com/telepresenceio/telepresence/issues/1607. I know that a lot of telepresence users are stuck on 1.0 because of your exact issue (it's very common to have services with multiple ports, especially with event driven architectures). So please upvote it.

At one point I did try a hack to make this work but could only commit a few hours to the cause. Also since, this is scheduled for the current milestone (note it was punted once already), I was hopeful that this is just around the corner.

**Comment by mumayuan** [comment]
agreed!
it is a duplicate with issue #1607 

Closing this and upvoting #1607
