### ISSUE TITLE
decompose swap-deployment into separate intercept and clone operations

### ISSUE THREAD

**Issue by rhs** [telepresenceio/telepresence#257]
I've been using telepresence in my dev workflow, primarily via swap-deployment, and it occurs to me that while this is quite useful, it is actually combining two logical things which would be useful on their own:

The ability to clone an existing deployment while substituting the telepresence proxy would enable me to locally develop in an environment consistent with the remote cluster without needing to impact/divert traffic to the telepresence proxy. This would give me the behavior of swap-deployment but in a "read-only" way with respect to cluster initiated traffic.

The ability to independently switch the remote service to point to my cloned proxy would then allow me to opt into the full service intercept behavior of swap-deployment.

**Comment by ofpiyush** [comment]
@rhs can you check if #407 solves all your use cases?

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2, since `telepresence connect` and `telepresence intercept` are separate commands. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
