### ISSUE TITLE
the server has asked for the client to provide credentials

### ISSUE THREAD

**Issue by burrsutter** [telepresenceio/telepresence#2585]
**Describe the bug**
Attempting to use the setup_dev_env.sh or telepresence connect seems to result in the same error
"the server has asked for the client to provide credentials"
https://www.screencast.com/t/PhJG25BjgzTg
https://www.screencast.com/t/MUOtAHSCa

[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/8703665/telepresence_logs.zip)

**To Reproduce**
See screenshots above

**Expected behavior**

**Versions (please complete the following information):**
 - Output of `telepresence version`
Client: v2.6.0 (api v3)
Root Daemon: v2.6.0 (api v3)
User Daemon: v2.6.0 (api v3)

 - Operating system of workstation running `telepresence` commands
 MacOS 12.3.1 (M1)
 
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
The one from ambassador cloud

**Comment by thallgren** [comment]
I see this in the `connector.log`:
```
unable to track k8s cluster: stat ./emojivoto_k8s_context.yaml: no such file or directory
```
That's likely caused by the fact that the Telepresence connector daemon wasn't started in the same directory as that kubeconfig was downloaded to. This can be caused by two things:
1. You started telepresence somewhere else originally so the daemon was already up and running.
2. You didn't start `setup_dev_env.sh` from the directory where it resides, which would have the same effect.

The remedy regardless is to first to do the following:
```
$ telepresence quit -ur
$ cd <your git clone of emojivoto>/emojivoto-web-app/js
$ ./setup_dev_env.sh
```

**Comment by cindymullins-dw** [comment]
To add to this for future reference, if you need to input credentials to access your cluster, the general steps you should take are:

1. Set your `kubeconfig`
2. Log into your cluster (then check that you can `kubectl get` resources in your cluster)
3. Run `telepresence connect`

The order matters because the Telepresence daemons need to know that you are able to log into your cluster. If you start Telepresence without logging in, the daemons will not have access to the credentials yet. The daemons might also not be aware of your login if you switch directories between logging in to your cluster and connecting Telepresence. To remedy the daemons trying to start without knowing the credentials, just simply quit them to get rid of the processes, and reconnect:

1. `telepresence quit -s`
2. `telepresence connect` again
