### ISSUE TITLE
--context flag reported as deprecated and ignored, but still listed in -h for commands and expected to work

### ISSUE THREAD

**Issue by Rylab** [telepresenceio/telepresence#2613]
**Describe the bug**
The --context kubernetes flag is still listed in the -h for most commands, yet is being ignored with the error:

use of global flag '--context' is deprecated and its value is ignored

**To Reproduce**
0. Have multiple kubernetes contexts setup (e.g. remote-dev-cluster and local-cluster)
1. When I run 'telepresence list --context=local-cluster' or 'telepresence list --context=remote-dev-cluster'
2. I see 'use of global flag '--context' is deprecated and its value is ignored'
3. So I look at 'telepresence list -h'
4. And see that this should still be supported

**Expected behavior**
I would hope to be able to switch between my local and remote kubernetes clusters, and list/intercept their services without having to constantly quit and reconnect.

**Versions (please complete the following information):**
 - Output of `telepresence version`
Client: v2.6.4 (api v3)
Root Daemon: v2.6.4 (api v3)
User Daemon: v2.6.4 (api v3)

 - Operating system of workstation running `telepresence` commands
Mac OS 12.4
 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
minikube v1.25.2, and Google Kubernetes Engine 1.23.2

**Comment by thallgren** [comment]
Some commands, like the `telepresence connect` list the `--context` flag, and also acts on it. It used to be a global flag, and the most common use was to repeat it for all commands in a script. Rather than breaking that, we decided to deprecate the flag for the commands where it no longer makes sense to have it.

If you want to do a `telepresence list` with a specific context, then do a `telepresence connect --context <your context>` first and then `telepresence list`.

The `telepresence list` command should not include those flags in its help. I see that it does, and we'll have to fix that.

**Comment by Rylab** [comment]
That makes sense, thank you.
