### ISSUE TITLE
Telepresence doesn't tunnel IPs in pod range

### ISSUE THREAD

**Issue by KarolisL** [telepresenceio/telepresence#264]
I'm using Kubespray's default service/pod ip ranges:
```
kube_service_addresses: 10.233.0.0/18
kube_pods_subnet: 10.233.64.0/18
```

Telepresence correctly detects the service IP range, but fails to route traffic to pods. This gets in a way when trying to access particular applications via headless k8s-services, e.g., kafka.

Is there an option to manually specify svc/pod ip ranges?

Also, maybe it would be worth to add CIDR support for `--also-proxy` option, e.g., `telepresence --also-proxy 10.233.64.0/18` would partially solve my problem.

```
$ telepresence --version
0.63
```

**Comment by ark3** [comment]
Thanks for the feature request. Both approaches are do-able. I'll look into them this week.

**Comment by burdiyan** [comment]
Any news about that?

For some reason I can access pod IPs on my GKE cluster, but not with minikube on my mac.

And `--also-proxy` does not allow specify CIDR for me for some reason.

Anyway, in Minikube, accessing a POD by IP is not working for me with Telepresence. I tried to spin up minikube both with VirtualBox driver and Hyperkit.

**Comment by KarolisL** [comment]
@burdiyan Looks like #384 was merged which allows CIDRs in `--also-proxy`.

At least from git history, it looks like it was released in `0.73`. Have you tried that version?

**Comment by richarddli** [comment]
@burdiyan If you could open up a separate issue on your Minikube problem (with a full `telepresence.log), we can investigate it. 

@karolisl does `0.73` improve things for you and let you workaround the issue?

**Comment by KarolisL** [comment]
@richarddli Yes, this can be used as a workaround (haven't tested yet, might do so after few weeks).

I'd suggest leaving this ticket open because having to manually specify the CIDR might be inconvenient when working with multiple clusters which have different pod network range.

**Comment by burdiyan** [comment]
Yes, I finally was able to specify pod's CIDR and connect to it. BUT, some VERY crazy things started happening, and it's only affecting local kubernetes cluster. I've tried that with minikube (virtual box and hyperkit drivers), and also Docker for Mac edge version that brings kubernetes cluster as well.

So the thing is that if I specify `--also-proxy` with the CIDR of my pods, suddenly I'm not able to connect to the internet from my machine. It happens right after the first time I connect to a POD by IP. Before it's working fine. But not afterwards. Normally I have Google's DNS servers (8.8.8.8, 8.8.4.4) set up on the host machine, but even removing those to default DNS of my ISP behaves similarly.

As soon as I close telepresence, internet start working.

That's super weird, and I can't explain to myself how that can be happening.

It's crazy that there is still no official and working solution for just bridging your host's network with local Kubernetes network for easy development, and I'm so glad you guys are doing something in that field!

I had to spin up OpenVPN as a pod, forward it's port to my local machine and use OpenVPN client on my Mac in order to make it work as I want. Basically doing the same as telepresence, but with OpenVPN instead of sshuttle.

**How to reproduce**

Mac OS High Sierra.

1. Spin up minikube cluster.
2. `kubectl run nginx --image nginx:alpine`.
3. Figure out pod's IP and it's CIDR.
4. Run `telepresence --also-proxy` with the CIDR.
5. Curl the nginx pod's IP.
6. Check if your internet is working.
7. `kubectl expose deploy nginx --port 80`.
8. Check if `curl nginx.default.svc.cluster.local` is working.

If you run telepresence without `--also-proxy` you can connect to services, but not to pods.

Maybe telepresence should automatically identify pod's CIDR and forward it as well? 

BTW using telepresence with a GKE cluster works without `--also-proxy` and I can connect to my pods by IP, so the issue seems to be only for local kubernetes clusters.

**Comment by saumitrabhave** [comment]
I think this issue relates more to `vpn-tcp` method, but the same behviour is observed in `--docker-run` as well.
I tried from alpine shell in docker(via `--docker-run`), i can see that I am able to `wget` services which are either `external`(with using `--also-proxy`) or have `clusterIP` assigned ... but for headless services (which do not have clusterIP assigned but the forward to they Pod's IP directly) its not working ....
In my case ... headless service represents a MySQL Pod, which forwards the Pod IP `100.120.0.4` .... but from docker logs of `datawire/telepresence-local` I can see that following rules are added to iptables
firewall manager: setting up.
```
>> iptables -t nat -N sshuttle-12300
>> iptables -t nat -F sshuttle-12300
>> iptables -t nat -I OUTPUT 1 -j sshuttle-12300
>> iptables -t nat -I PREROUTING 1 -j sshuttle-12300
>> iptables -t nat -A sshuttle-12300 -j RETURN --dest 127.0.0.1/32 -p tcp
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 100.96.2.0/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 100.96.3.0/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 100.96.1.0/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 100.96.0.0/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 100.96.8.0/24 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 100.64.0.0/13 -p tcp --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 8.8.8.8/32 -p udp --dport 53 --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 8.8.4.4/32 -p udp --dport 53 --to-ports 12300 -m ttl ! --ttl 42
>> iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 224.0.0.252/32 -p udp --dport 5355 --to-ports 12300 -m ttl ! --ttl 42
```
I dont see a rule for `100.120.*.*` . 

issue # #391  should solve this problem for `--docker-run` (or `--method container`)

**Comment by derimagia** [comment]
Having the same issue with having headless services. I think a solution could be to use the endpoints instead of the ClusterIPs since headless services will still have endpoints. See https://github.com/datawire/telepresence/blob/9a7772c20b0d5e22ba27df09843e50e4e0fe188a/telepresence/vpn.py#L194-L204

**Comment by ryanjbaxter** [comment]
I would also like to see this resolved.  For me the fabric8io client is returning the pod ip address to my app which is not able to be resolved unless I specify `--also-proxy`.

**Comment by donnyyung** [comment]
It seems there are a few issues here but the main issue of Telepresence not tunneling IPs in the pod range should no longer be an issue in Telepresence 2 (we also have the also-proxy feature https://www.getambassador.io/docs/telepresence/latest/reference/config/#alsoproxy).  If the root issue is still occurring in telepresence 2, please re-open.

Additionally, if you raised a sub-issue here that still is a problem in Telepresence 2, please open a new ticket. Thank you!

**Comment by donnyyung** [comment]
It seems there are a few issues here but the main issue of Telepresence not tunneling IPs in the pod range should no longer be an issue in Telepresence 2 (we also have the also-proxy feature https://www.getambassador.io/docs/telepresence/latest/reference/config/#alsoproxy).  If the root issue is still occurring in telepresence 2, please re-open.

Additionally, if you raised a sub-issue here that still is a problem in Telepresence 2, please open a new ticket. Thank you!
