### ISSUE TITLE
logout with --http-header

### ISSUE THREAD

**Issue by silenceGuo** [telepresenceio/telepresence#2729]
Thanks for mentioning Telepresence as such a great tool. I wonder how to use the --http-header option without logging into Ambassador Cloud. If it is not supported now, I hope it will be supported in the future, otherwise it can only proxy all tcp traffic. I don't want to affect online traffic

**Comment by cindymullins-dw** [comment]
Hi @silenceGuo , if you’re not able to connect to Ambassador Cloud, for example because of an air gapped environment, you can use an [air gapped license](https://www.getambassador.io/docs/telepresence/latest/reference/cluster-config/#air-gapped-cluster).  You would need to login once to get the air gapped license but once you apply it to your cluster you’ll be able to login without logging into Ambassador Cloud each time by adding [‘skip login’ to your config.yaml file](https://www.getambassador.io/docs/telepresence/latest/reference/config/#cloud).

**Comment by rjshrjndrn** [comment]
Is it possible to route the traffic with only http header, without preview url?
