### ISSUE TITLE
[Enhancement] More resilient DNS handling with the traffic manager

### ISSUE THREAD

**Issue by DanielYWoo** [telepresenceio/telepresence#2760]
**Describe the bug**
cannot use k8s DNS

```
❯ curl -sv https://kubernetes.default.svc
* Could not resolve host: kubernetes.default.svc
```
log files: 
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/9433230/telepresence_logs.zip)

**To Reproduce**
1. When I run 'telepresence connect'
2. I see 'connected'
3. So I look at 'curl https://kubernetes.default'
4. See error `could not resolve host`

**Expected behavior**
Can resolve the hostname.

**Versions (please complete the following information):**
 - Output of `telepresence version`
Client: v2.7.1 (api v3)
Root Daemon: v2.7.1 (api v3)
User Daemon: v2.7.1 (api v3)

 - Operating system of workstation running `telepresence` commands
MacOS Monterey

 - Kubernetes environment and Version [e.g. Minikube, bare metal, Google Kubernetes Engine]
Docker Desktop

**VPN-related bugs:**
`telepresence test-vpn` shows empty result.
 - Which VPN client are you using? F5 Access
 - Which VPN server are you using? F5
 - How is your VPN pushing DNS configuration? It may be useful to add the contents of /etc/resolv.conf. Mac does not use it.

**Additional context**
I cannot reproduce it but it surely happens a lot. I can make it work by restarting the traffic manager as @peakschris suggested, hence this must be related to the initialization process of the traffic manager. If we can periodically retry for DNS handling, can we get this fixed?

**Comment by raphaelreyna** [comment]
Just to get some more info: is this on an Intel mac?

**Comment by DanielYWoo** [comment]
> Just to get some more info: is this on an Intel mac?

It's on an Apple Silicon Mac. BTW, there is nothing under /etc/resolver.

**Comment by DanielYWoo** [comment]
It reports connected, and there is no error in logs, but it just does not work.

```
❯ telepresence status
W0828 16:28:35.660327    5869 native_arm64.go:52] Could not read /proc/cpuinfo: open /proc/cpuinfo: no such file or directory
W0828 16:28:35.660354    5869 native_arm64.go:177] Could not read /proc/self/auxv: open /proc/self/auxv: no such file or directory
Root Daemon: Running
  Version   : v2.7.2 (api 3)
  DNS       :
    Remote IP       : <nil>
    Exclude suffixes: [.arpa .com .io .net .org .ru]
    Include suffixes: []
    Timeout         : 8s
  Also Proxy : (0 subnets)
  Never Proxy: (1 subnets)
    - 127.0.0.1/32
User Daemon: Running
  Version         : v2.7.2 (api 3)
  Executable      : /Users/.../Library/Application Support/telepresence/telepresence-pro
  Install ID      : 65e27462-740c-4796-945e-1e81bafbe98d
  Ambassador Cloud:
    Status    : Logged in
    ...
  Status            : Connected
  Kubernetes server : https://kubernetes.docker.internal:6443
  Kubernetes context: docker-desktop
  Intercepts        : 0 total
```

**Comment by matt-phylum** [comment]
I had a similar issue and in the output of `kubectl logs -n ambassador deployment/traffic-manager` there was a message `warning Could not determine DNS ClusterIP`. After `kubectl rollout restart -n ambassador deployment/traffic-manager`, traffic-manager did resolve the DNS IP, and then `telepresence quit -r` `telepresence connect` fixed /etc/resolver.

In my case, it looks like there is a race condition in cluster startup where if the DNS service is not ready before traffic-manager starts, traffic-manager fails to initialize.

**Comment by peakschris** [comment]
> I had a similar issue and in the output of `kubectl logs -n ambassador deployment/traffic-manager` there was a message `warning Could not determine DNS ClusterIP`. After `kubectl rollout restart -n ambassador deployment/traffic-manager`, traffic-manager did resolve the DNS IP, and then `telepresence quit -r` `telepresence connect` fixed /etc/resolver.

I had this exact issue, and restarting traffic-manger resolved it for me. Thank you!

**Comment by DanielYWoo** [comment]
upgraded to 2.7.3, exactly same here as @peakschris 
Is it possible to have the Traffic Manager periodically retry with the DNS, even if it fails at startup?

**Comment by noirbizarre** [comment]
Same issue on Linux (ArchLinux to be more precise) with `systemd-resolved`.

`tel0` interface is created but without any `DNS Server` nor `DNS Domain` set. Here the output of `resolvectl` (cropped to `tel0`):
```
Link 16 (tel0)
Current Scopes: LLMNR/IPv6
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```
And `telepresence status`
```
Root Daemon: Running
  Version   : v2.7.3 (api 3)
  DNS       :
    Remote IP       : <nil>
    Exclude suffixes: [.arpa .com .io .net .org .ru]
    Include suffixes: []
    Timeout         : 8s
  Also Proxy : (0 subnets)
  Never Proxy: (0 subnets)
User Daemon: Running
  Version         : v2.7.3 (api 3)
  Executable      : /usr/bin/telepresence
  Install ID      : 038d9033-6d4d-40e2-a003-b2daed48f4c5
  Ambassador Cloud:
    Status    : Logged out
    User ID   : 
    Account ID: 
    Email     : 
  Status            : Connected
  Kubernetes server : https://0.0.0.0:40011
  Kubernetes context: k3d-minivault
```

By the way, it was working juste fine on `2.6.8` until I updated yesterday on `2.7.3` (see the package: https://aur.archlinux.org/packages/telepresence2)
DNS resolution broken also mean telepresence is broken because intercepted environment is not working anymore (because names does not resolve). Downgraded to `2.6.8` until fixed.

**Comment by cindymullins-dw** [comment]
@DanielYWoo, we've noticed this behavior as well for example when the computer goes into sleep mode.  If DNS resolution is corrupted for some reason you have to restart the Traffic Manager.  As a feature request, perhaps it would be useful to update the title to reference the periodic DNS retry that might resolve it.

**Comment by jjmachan** [comment]
is anyone working on this? I'm facing the same issue too. Faced this in 2.7 and 2.6 as well. Works initially

logs
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/9693333/telepresence_logs.zip)

**Comment by thallgren** [comment]
@jjmachan judging from your logs, you are not even able to connect to the cluster, so you kubeconfig is probably not OK.
```
connector/session : unable to track k8s cluster: initial cluster check failed: Get "https://192.168.39.195:8443/version": net/http: TLS handshake timeout
```
Can you do a `kubectl version` and get the "Server Version"?

**Comment by thallgren** [comment]
@noirbizarre could you try the following:
```console
$ telepresence quit -ur
$ telepresence loglevel debug
$ telepresence connect
$ telerepsence gather-logs
```

**Comment by thallgren** [comment]
@DanielYWoo the root cause of your problem is that the traffic manager reports "Could not determine DNS ClusterIP". This happens when it cannot find the cluster's DNS resolver. It tries to contact `kube-dns.kube-system`, `coredns.kube-system`,  and `dns-default.openshift-dns`, but fails. You'll need to provide something that succeeds in your Helm chart by providing the values `dnsServiceName` and `dnsServiceNamespace`. Please see our Helm chart [README](https://github.com/telepresenceio/telepresence/blob/release/v2/charts/telepresence/README.md) for more info.

**Comment by jjmachan** [comment]
@thallgren here is the server version
```
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:23:26Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by thallgren** [comment]
@jjmachan so then you are able to connect to the cluster using `kubectl`? In that case, it's very surprising that you'd get `initial cluster check failed: Get "https://192.168.39.195:8443/version": net/http: TLS handshake timeout` when you try to connect using `telepresence`, because all it does at that stage, is to retrieve the cluster version. Are you using different kubeconfig settings?

**Comment by jjmachan** [comment]
got it! This is probably because I restarted minikube but what I experience is sometimes kubectl is not able to connect to the cluster and I get a timeout error when performing basic tasks. I still haven't been able to figure out how to reproduce this (how using telepresence connect leads to this) but I'll share that once I have it. (if you have some idea on how to create that that would help too)

**Comment by DanielYWoo** [comment]
> It tries to contact kube-dns.kube-system, coredns.kube-system, and dns-default.openshift-dns, but fails. You'll need to provide something that succeeds in your Helm chart by providing the values dnsServiceName and dnsServiceNamespace. 

I have coredns.kube-system and they are the default values in the helm chart, they are correct, the traffic manager works in 95% of the time. Ocassionally, when I restart my laptop or close the lid for a while, or connect to a VPN, anyway, somehow it probably has some glitches in coredns. So we just need a more resilient DNS handling, maybe periodically retry if it fails?

e.g., when none of these DNS systems can be used, we can log an error, sleep a few seconds and try again until we make it.
https://github.com/telepresenceio/telepresence/blob/45ee4cd1325990af5689f8c291fc9d24c7b81288/cmd/traffic/cmd/manager/internal/cluster/info.go#L129-L131

**Comment by thallgren** [comment]
Thanks @DanielYWoo, that's very useful info. And yes, retrying this in case of failure sounds very reasonable.
