### ISSUE TITLE
Telepresence package on Fedora includes conntrack but does not look for it in the right place

### ISSUE THREAD

**Issue by plombardi89** [telepresenceio/telepresence#278]
### What were you trying to do?

Upgraded Telepresence to `0.65-1` and then ran `telepresence --run-shell`

### What did you expect to happen?

Telepresence would start a shell.

### What happened instead?

```bash
plombardi@palwork ~/w/k7t-be> telepresence --run-shell
Please install conntrack
See the documentation at http://telepresence.io for more details.
```

### Expectations

I'm not sure what `conntrack` is or how to install it. I went to telepresence.io as instructed and the install instructions for Fedora 25 do not indicate I need to do anything differently or install any 3rd party software.

**Comment by plombardi89** [comment]
So... I went to install `conntrack` and low and behold I already have it.

```bash
plombardi@palwork ~/w/k7t-be> sudo -s dnf install conntrack
Package conntrack-tools-1.4.3-1.fc25.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
```

So it appears this is a bug in Forge.

**Comment by rhs** [comment]
FWIW, this worked for me on fedora 25 with exactly the same version of conntrack-tools that you have.

**Comment by rhs** [comment]
For the record, @plombardi89 and I did a little out of band environment comparisons. It looks like the critical difference in this case is that `/usr/sbin` is in my path, but it is not in @plombardi89's path, and this is where `conntrack` lives.

A possible fix for this would be for telepresence to append `/usr/sbin` to the path that it uses to search for conntrack. This would allow users to override paths if they wanted a specific conntrack to be used, but would not break if `/usr/sbin` is not in the users path.

**Comment by ark3** [comment]
I added a bit more clarity in 2670fbf. Now Telepresence will tell you something like

    (Ran "which conntrack" to check in your $PATH.)

if that check fails. Checking _extra_ locations is also an option, but I think the main problem here was that Telepresence did not report what it was really trying to do that failed. What do you think @plombardi89 @rhs?

**Comment by itamarst** [comment]
1. Telepresence needs conntrack on newer Fedora. If it's not available, e.g. because /usr/sbin isn't in $PATH, by default, that's a bug.
2. Given Telepresence is packaged for Fedora specifically, it's a supported platform, it's legit and desirable to add /usr/sbin to $PATH so it works on Fedora.
3. The checks for existence are mainly a debugging use case at this point, given we have packaging (originally people needed to install stuff manually). That is, a failure indicates either a bug in Telepresence or a *really* messed up environment. In this case it's the former. So one could argue that any of these warnings should automatically come with a "please file a bug" prompt.

**Comment by plombardi89** [comment]
Just hit this again :(
