### ISSUE TITLE
systemd-resolveD DNS sanity check fails with local MicroK8s

### ISSUE THREAD

**Issue by davidecavestro** [telepresenceio/telepresence#2811]
**Describe the bug**
 When connecting telepresence to a local microk8s, the sanity check fails for systemd-resolved based DNS, hence falling back to the legacy DNS server

**To Reproduce**
1. When I run `telepresence connect` having a local microk8s as k8s context
2. I see _resolver did not receive requests from systemd-resolved_ within daemon logs
3. This happens after telepresence has configured the _tel0_ TUN device with a a _tel2-search_ domain and failed checking for 2 secs if query works properly
4. It logs _Unable to use systemd-resolved, falling back to local server_
5. Then the legacy server works properly, but we loose resolved-related features such as per-link config and so on

**Expected behavior**
When using a local k8s cluster we should be able to leverage the resolved config related to the tel0 device when resolving names in the form of <service>.<namespace>.

**Versions (please complete the following information):**
 - Output of `telepresence version`

> Client: v2.7.6 (api v3)
> Root Daemon: v2.7.6 (api v3)
> User Daemon: v2.7.6 (api v3)

 - Operating system of workstation running `telepresence` commands: Ubuntu 20.04 LTS
 - Kubernetes environment and Version: MicroK8s v1.25.2

**Additional context**
Issue filled after a [Slack message](https://datawire-oss.slack.com/archives/CAUBBJSQZ/p1665418007349829) discussed at the weekly help session.

Download [this Vagrantfile](https://gist.github.com/davidecavestro/bee90919f6ac3c43c2122088d3186393) to easily spin-up an Ubuntu vm and check the issue on a live box, After the `vagrant up` command completes, you get a fresh telepresence_logs.zip and a running vm you can play with using `vagrant ssh`

See also related issue #2809 
 #
[telepresence_logs.zip](https://github.com/telepresenceio/telepresence/files/9763678/telepresence_logs.zip)

**Comment by cindymullins-dw** [comment]
We think there are some extra steps needed when using Telepresence on microk8s involving DNS and RBAC add ons, and to add subnets for the TUN device.   Could you have a look at the [`alsoproxy` doc here](https://www.getambassador.io/docs/telepresence/latest/reference/cluster-config/#alsoproxy).

**Comment by thallgren** [comment]
@davidecavestro thanks for providing an excellent reproducer. It made it very easy to analyze the problem, which is the following:

1. The CIDRs of the microk8s cluster are already available on the host, consequently, they are not added to the TUN-device because that would cause a conflict.
2. The Telepresence DNS resolver for systemd-resolved tries to add a DNS-resolver for an IP in a cluster CIDR, which as a result of no 1, isn't routed. So that fails.
3. Telepresence falls back to the legacy resolver, which does its magic using iptables instead of using the TUN device.

Although things work, thanks to the legacy resolver, this isn't quite right. I'll investigate if we can find a better solution.

**Comment by thallgren** [comment]
I've done some experimenting with microk8s. When using `systemd.resolved`, we need to call `SetLinkDNS` on a network interface that isn't managed. This is not a problem when we create a TUN-device with a CIDR that covers the actual DNS IP.

The problem arises when we add the CIDR needed to include the DNS IP (we have to, because the cluster CIDR's are already available, so we can't add them). From the looks of it, microk8s restarts the node every time the CIDR range for an interface device changes, causing the traffic-manager to vanish, and hence a connection drop. This means that using `systemd.resolved` on a microk8s seems to be a no-go. At least with the setup used in the sample Vagrantfile.

The restart can be observed by doing:
```console
vagrant@ubuntu-focal:~$ microk8s kubectl -n ambassador logs -f traffic-manager-6588d59df-jn5rd 
```
in one terminal and then:
```console
vagrant@ubuntu-focal:~$ sudoip a add 192.168.0.0/24 dev tel0
```
in another.

**Comment by davidecavestro** [comment]
Thanks... we noticed microk8s badly reacts to device changes, this in turn leads to a lot of pod restarts, among other things.
Will look into that.
