### ISSUE TITLE
better validation for telepresence intercept flags

### ISSUE THREAD

**Issue by nicks** [telepresenceio/telepresence#2974]
**Please describe your use case / problem.**

I ran this command:

```
telepresence intercept db-3306 --workload db --namespace nicks-deployment-4l6cx --service db --port 3306
```

I got this error:

```
error: connector.CreateIntercept: Deployment db.nicks-deployment-4l6cx has multiple interceptable ports in service db.
Please specify the port you want to intercept by passing the --port=<local:svcPortName> flag.
```

I could not figure out for the life of me what this error was telling me to do! I was already passing the `--port` flag!

It turned out that the error message was the wrong format.

**Describe the solution you'd like**
I would like the error message to validate the flag value instead, e.g., 

```
error: port invalid value: 3306. Expected format <local:svcPortName>
```

**Describe alternatives you've considered**
I could also imagine auto-inferring the service port name by assuming it matches the local port number

**Versions (please complete the following information)**
OSS Client     : v2.10.1
OSS Root Daemon: v2.10.1
OSS User Daemon: v2.10.1
Traffic Manager: v2.10.1

**Additional context**
Nope, thank you!!

**Comment by cindymullins-dw** [comment]
Hi @nicks , as I understand --port 3306 is not an invalid value, it's just incomplete.  If you specify only one port Telepresence will assume that's your local port and then it will try to auto-detect your Service port in use.  So with multiple Service ports as in your case, you'd have to specify both local and Service.  So it would seem - with that bit of knowledge - the error message is correct because it does show that two-part port configuration which is what is required.
