### ISSUE TITLE
can't connect to existing Kubernetes cluster on AWS

### ISSUE THREAD

**Issue by Ed42** [telepresenceio/telepresence#298]
### What were you trying to do?

trying to run your "hello world" example in an existing kubernetes cluster (AWS)

### What did you expect to happen?

"hello, world"

### What happened instead?

got this error, however:

to run kubectl localy and connect to our AWS cluster I need to run this:

`kubectl --kubeconfig=<path to K8s config file> ...`

do I somehow pass the existing config to telepresence?

### Automatically included information

Command line: `['/usr/bin/telepresence', '--context', 'kube-aws-xxx-dev-k8s-context', '--namespace', 'int', '--new-deployment', 'hello-world', '--expose', '8080']`
Version: `0.67`
Python version: `3.5.3 (default, Sep  7 2017, 16:23:57) 
[GCC 6.3.0 20170406]`
kubectl version: `Client Version: v1.7.6`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Linux ubuntu1704 4.10.0-35-generic #39-Ubuntu SMP Wed Sep 13 07:46:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/bin/telepresence", line 257, in call_f
    return f(*args, **kwargs)
  File "/usr/bin/telepresence", line 2270, in go
    runner = Runner.open(args.logfile, kubectl_or_oc(server), args.verbose)
UnboundLocalError: local variable 'server' referenced before assignment

```

Logs:

```
Not available
```

**Comment by ark3** [comment]
Thanks for the bug report. Telepresence is failing to find the correct cluster because it doesn't have the configuration information that you normally pass to `kubectl`. However, rather than telling you that, it's crashing. Sorry about that!

Set the `KUBECONFIG` environment variable to tell Telepresence (or really, to tell `kubectl`) your cluster configuration. Then you will not need to pass `--kubeconfig=...` to the `kubectl` command explicitly. This will allow Telepresence to access the correct cluster.

```shell
export KUBECONFIG=<path to K8s config file>
kubectl get pods  # etc.
telepresence [...]  # etc.
```

or

```shell
env KUBECONFIG=<path to K8s config file> telepresence [...]   # One line version
```

Check out [the Kubernetes documentation](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#the-kubeconfig-environment-variable) for more info on that environment variable.

**Comment by Ed42** [comment]
Thanks for the awesome quick response, that worked. Now I need to find out how to contact AWS managed services when running a local service. First thing the service does is try to contact redis.

**Comment by Ed42** [comment]
in case it's of any use I've attached an ubuntu crash report for the node process using `inject-tcp` (I removed the coredump as it's quite big, let me know if you need it).

[node.crash.gz](https://github.com/datawire/telepresence/files/1326925/node.crash.gz)

**Comment by Ed42** [comment]
also `telepresence.log` files when using `vpn-tcp` and `inject-tcp`, just in case

[telepresence-logs.tar.gz](https://github.com/datawire/telepresence/files/1326940/telepresence-logs.tar.gz)

**Comment by richarddli** [comment]
The actual issues are (1) node crashes with inject-tcp, (2) DNS is not working correctly with vpn-tcp (nslookup works but other stuff doesn't)

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
