### ISSUE TITLE
overwrite intercepts

### ISSUE THREAD

**Issue by nicks** [telepresenceio/telepresence#3151]
**Please describe your use case / problem.**
I frequently get telepresence into a state where the session is orphaned. Creating a new intercept consistently rejects with an error:

```
telepresence intercept: error: connector.CreateIntercept: Failed to establish intercept: intercept in error state AGENT_ERROR: e1c5be84-6aae-4655-beba-12b83ce21dec:repos-new-80 conflicts with "tcp" mechanism of intercept 59954361-6eaa-497d-b13e-d916fdc7c40b:repos-new-80
```

Once I get into this state, the only way to fix it is to completely uninstall the traffic manager and re-install it.

**Describe the solution you'd like**
Ideally, `telepresence intercept` would accept an `--overwrite` argument. If there was a conflict, the traffic manager would automatically delete the conflicting intercept before attaching the new one.

**Describe alternatives you've considered**
I think it would also be reasonable if I could use `telepresence list` / `telepresence leave` to list / delete intercepts created by other sessions.

**Versions (please complete the following information)**

```
telepresence version
An update of telepresence from version 2.12.2 to 2.13.1 is available. Please visit https://www.getambassador.io/docs/telepresence/latest/install/upgrade/ for more info.
Client         : v2.12.2
Root Daemon    : v2.12.2
User Daemon    : v2.12.2
Traffic Manager: v2.12.2
```

**Additional context**
none

**Comment by cindymullins-dw** [comment]
Can you try just deleting the traffic agent on the pod you’re trying to intercept?  If that resolves the error it would be less invasive than deleting the traffic manager and admin/permissions to re-install it.

**Comment by nicks** [comment]
The last time I had this problem, deleting the traffic agent from the pod didn't fix the problem. :disappointed:

**Comment by jcornick-alabs** [comment]
@nicks can you send us the command you used to install TP and the command you used to create the intercept?  Which TP binary are you using, is it the OSS one (download location would tell us that)?

**Comment by nicks** [comment]
my install script looks like:

```
curl -fsSL https://app.getambassador.io/download/tel2/linux/${TARGETARCH}/${TELEPRESENCE_VERSION}/telepresence -o telepresence && \
    install -o root -g root -m 0755 telepresence /usr/local/bin/telepresence && \
    rm telepresence
```

i don't know which intercept command is causing it; i'll see if i can narrow down a repro case.

**Comment by thallgren** [comment]
Adding a `--overwrite` is problematic, because there's no way of telling that the intercept in question is your intercept. I don't think we want to provide a flag whereby you can kill someone elses intercept.

The solution for you is probably to change the "time to live" for the session. It's currently 24 hours. Try setting it to 10 seconds instead. That'll effectively kill the intercept 10 seconds after the client stop polling the traffic-manager (which it does if your laptop goes to sleep or disconnect).

```console
$ telepresence helm upgrade --set client.connectionTTL=10s
```

Side note. Given that you have admin permissions to the cluster, a less drastic way of getting rid of the intercept is to scale the traffic-manager deployment to zero, then back up to one.
```console
$ kubernetes -n ambassador scale deployment traffic-manager --replicas=0
$ kubernetes -n ambassador scale deployment traffic-manager --replicas=1
```

**Comment by nicks** [comment]
ya, i had it happen again, and confirmed that uninstalling the agent doesn't fix it. you have to uninstall the whole traffic manager.

i'll see if i can pin down a repro case later today.

**Comment by thallgren** [comment]
Any news on this? Also, I never suggested uninstalling the agent.

**Comment by nicks** [comment]
client.connectionTTL=10s fixed the problem for us! is there any reason that's not the default?

I tracked the root cause down to a case where the network namespace where i had the daemon running was shut down before the process..

**Comment by thallgren** [comment]
The reason we introduced this configurable timeout was that a lot of users complained that their intercepts were dropped when they closed the lid on their laptops, or otherwise lost connection (travelling home for instance). The default timeout of 24 hours was to ensure that you could safely close the lid at the end of your day and your intercept would still be alive when you opened it the next morning.

So, it helps many in normal day-to-day work but it isn't ideal when your client dies ungracefully. We didn't base the default setting on the latter.
