### ISSUE TITLE
Add examples for setting up 'Team-Mode' via Helm Chart

### ISSUE THREAD

**Issue by Allure996** [telepresenceio/telepresence#3246]
**Please describe your use case / problem.**
Hello, today I set up team mode via Helm Chart, without using the command `telepresence helm upgrade --team-mode`, since I deploy traffic-manager from a Runner where I have no `telepresence` CLI installed.
I succeded in doing that by searching inside this repo, in `templates/` folder, looking for the traffic-manager configmap.

Without this, I wouldn't be able to achieve my goal.

I looked throughout all this repo searching for any reference for team-mode, but I could not find any.

Just for clarity, I set up my `values.yaml` as follow

![image](https://github.com/telepresenceio/telepresence/assets/98020456/f1924340-6b7d-4e49-9d1f-dad287b65627)

**Describe the solution you'd like**
I think it would be awesome to improve the README.md and the values.yaml

**Describe alternatives you've considered**
-

**Versions (please complete the following information)**
  ```
Client         : v2.13.1
Root Daemon    : v2.13.1
User Daemon    : v2.13.1
Traffic Manager: v2.14.0
```
  - Kubernetes Environment and Version: 1.24

**Comment by knlambert** [comment]
Hello @Allure996, the [team mode ](https://www.getambassador.io/docs/telepresence/latest/concepts/modes#team-mode) is part of the Telepresence pro product (Fremium), while this is OSS. So you won't find its source code here since it is proprietary.

We recently split our [documentation](https://www.getambassador.io/docs/telepresence-oss) in two parts to avoid any confusion, so you can check it if you're in doubt when it comes to the keys differences.

**Comment by cindymullins-dw** [comment]
Closing as the question has been answered.
