### ISSUE TITLE
No sudo

### ISSUE THREAD

**Issue by justinmchase** [telepresenceio/telepresence#3284]
**Please describe your use case / problem.**
I'm on a corporate mac and admin access is restricted. I can do it but i have to jump through hoops and enter a long password over and over. Also it strikes me that nothing in this app really should require sudo. I don't need admin to interact with kubernetes so why should this app? Why are you trying to install a daemon for example? I can just run it in a process while I'm using it and not while I'm not. 

Please remove requirements for sudo.

**Describe the solution you'd like**
To never have to use sudo or enter my password or require root privileges.

**Describe alternatives you've considered**

**Versions (please complete the following information)**
  - Output of `telepresence version` (just in case the feature exists in future versions)

🤦 
```
> t version
Launching Telepresence Root Daemon
Need root privileges to run: /usr/local/bin/telepresence daemon-foreground /Users/jchase24/Library/Logs/telepresence '/Users/jchase24/Library/Application Support/telepresence'
Password:
```

  - Kubernetes Environment and Version
```
> k version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.25.9
```

**Additional context**
In a corporate environment so the machines are unusually locked down.

**Comment by knlambert** [comment]
Hello,

Telepresence needs sudo access because it modifies your network interfaces / dns configurations so your machine can behave like if it was a pod in the cluster. 

You can then resolve Kubernetes services without doing a port forward.

If you want to avoid the requirement for sudo access, you can use [the docker mode of Telepresence](https://www.getambassador.io/docs/telepresence-oss/latest/reference/docker-run) using `telepresence connect --docker`.

**Comment by justinmchase** [comment]
Thanks for the explanation.
