### ISSUE TITLE
Support using Certmanager to generate mutator-webhook-tls secret

### ISSUE THREAD

**Issue by PLWagner** [telepresenceio/telepresence#3353]
**Please describe your use case / problem.**

I use ArgoCD to deploy the Telepresence Helm chart in a Kubernetes cluster. As ArgoCD use the Helm template function to render manifests, the `lookup` function used in the template `agentInjectorWebhook.yaml` does not work as intended. 

The result in ArgoCD is a Telepresence app unsynced every 3 minutes because the TLS certificate is regenerated by Helm. 

Also, when the app is synchronized, the `upgrade-legacy` post-upgrade hook fails to run successfully because the `traffic-manager` pod did not restart to ensure using the newly generated TLS certificate. 

**Describe the solution you'd like**

I want to allow using Certmanager features to generate the certificate and use it with the `agentInjectorWebhook`.

**Describe alternatives you've considered**

Do nothing and wait until ArgoCD include the Helm build including this feature: https://github.com/argoproj/argo-cd/issues/5202. (It has been merged: https://github.com/argoproj/argo-cd/issues/5202#issuecomment-1644432182)

**Versions (please complete the following information)**

  - Output of `telepresence version`: `v2.15.1`
  - Kubernetes Environment and Version: `v1.26.7`

**Comment by msvticket** [comment]
I have made a local copy of the chart where I changed the behaviour to use cert manager instead of generating the secret in the helm chart. I could polish this up and make a pull request if there is any interest in getting it merged. I would base it on how it works in the aws-load-balancer-controller chart. See https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/templates/webhook.yaml
