### ISSUE TITLE
 If telepresence didn't get the necessary permissions the first time, restarting it with sudo doesn't work.

### ISSUE THREAD

**Issue by trukhinyuri** [telepresenceio/telepresence#3396]
If telepresence didn't get the necessary permissions the first time, restarting it with sudo doesn't work.
The solution is to forcibly kill the daemon (which doesn't have sudo permissions), but telepresence when run under sudo should do this itself.

trukhinyuri@trukhinyurisMBP ~ % **telepresence connect**     
Launching Telepresence User Daemon
Launching Telepresence Root Daemon
telepresence connect: error: connector.Connect: open /Users/trukhinyuri/Library/Caches/telepresence/sessions/minikube-default.json: permission denied

See logs for details (1 error found): "/Users/trukhinyuri/Library/Logs/telepresence/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .
trukhinyuri@trukhinyurisMBP ~ % **sudo telepresence connect**
telepresence connect: error: connector.Connect: open /Users/trukhinyuri/Library/Caches/telepresence/sessions/minikube-default.json: permission denied

See logs for details (3 errors found): "/Users/trukhinyuri/Library/Logs/telepresence/connector.log"
If you think you have encountered a bug, please run `telepresence gather-logs` and attach the telepresence_logs.zip to your github issue or create a new one: https://github.com/telepresenceio/telepresence/issues/new?template=Bug_report.md .
trukhinyuri@trukhinyurisMBP ~ % **sudo telepresence quit -s**
Telepresence Daemons quitting...done
trukhinyuri@trukhinyurisMBP ~ % **sudo telepresence connect**
Launching Telepresence User Daemon
Launching Telepresence Root Daemon
**Connected to context minikube, namespace default (https://127.0.0.1:61500)**

**Comment by cindymullins-dw** [comment]
Hi @trukhinyuri, did you initially use sudo with Telepresence perhaps to overcome permission requirements?  
If you install everything without elevated permissions you can use Telepresence without sudo.  However once you set these elevated privileges you won’t be able to get away from using sudo.  We don't recommend using sudo because it can confuse Telepresence, for example by creating files in the Library path which Telepresence will subsequently try to use.  You might be able to resolve this by removing those Library path files, or you can uninstall and install it again as a non-admin user.
