### ISSUE TITLE
Use service account in `telepresence intercept`

### ISSUE THREAD

**Issue by mausch** [telepresenceio/telepresence#3455]
**Please describe your use case / problem.**

I want to run `telepresence intercept` in a pod (my whole development environment lives in kubernetes).
The pod has /var/run/secrets/kubernetes.io/serviceaccount mounted as usual with a service account . 
I can run kubectl without needing to define any explicit contexts or kubeconfig.
Telepresence however complains that there is no context: `telepresence intercept: error: kubeconfig has no context definition`

As a workaround I build a kubeconfig from the details in /var/run/secrets/kubernetes.io/serviceaccount

**Comment by thallgren** [comment]
I suggest that you use `telepresence connect --docker`. A `telepresence status` will then tell you the name of the network that other containers should use in order to get access to the VIF that Telepresence creates (i.e. `docker run --network container:tp-default-default-cn` or similar). Another option is to use `telepresence connect --docker` and then do `telepresence intercept --docker-run (or --docker-build) -- <docker run options>`. That will run the container with the network configured, the volumes mounted, and the environment configured.

**Comment by thallgren** [comment]
If you want to know exactly how that container is started, use loglevel debug and then check the `cli.log`. The `docker run` command is logged there, complete with all options and flags.

**Comment by thallgren** [comment]
Closing this as a non-issue.
