### ISSUE TITLE
Connect speed

### ISSUE THREAD

**Issue by jckos** [telepresenceio/telepresence#3661]
Hello,
we are having long connection times to the cluster. Is it normal time or is it an issue by us please?

`telepresence connect --namespace=tpk*****`

> Launching Telepresence User Daemon

- 1s

> Launching Telepresence Root Daemon

- 1s

entered pass for sudo requirement

- 4-6 minutes

> Connected to context aks-ne*****, namespace tp***** (https://*********.privatelink.northeurope.azmk8s.io:443)

Expected behaviour:
It connects a bit faster.

Versions (please complete the following information):
OSS Client : v2.17.0
OSS Root Daemon : v2.17.0
OSS User Daemon : v2.17.0
OSS Traffic Manager: v2.17.0
Apple M1 14.4.1 (23E224) or Linux (even slower time)
cluster: AKS

**Comment by thallgren** [comment]
This is probably due to the traffic-manager taking a long time to respond with network information (subnets and DNS info). You can do some detective work to find out more by first enable debug logging, then reconnect, and then investigate the `daemon.log` file.

Add a file named `config.yml` to directory `"~/Library/Application Support/telepresence"` with the following content:
```
logLevels:
  userDaemon: debug
  rootDaemon: debug
```
Then, after a successful connect, investigate the content of `~/Library/Logs/telepresence/daemon.log`. You'll see when the daemon starts and when it receives the information about subnets etc.

If the traffic-manager is slow, you can debug that too. Try using `telepresence loglevel debug` after a successful connect. The disconnect and connect again. The logs from the traffic-manager pod (in namespace "ambassador") can provide helpful info.

Once debug level logging is enabled, you can also do `telepresence gather-logs` to gather all logs. Feel free to post them here if you want others to have a look.

All of that aside, I'd recommend upgrading to 2.19.1.

**Comment by cindymullins-dw** [comment]
You  might also try the [--mapped-namespaces](https://www.getambassador.io/docs/telepresence/latest/howtos/large-clusters#limiting-at-connect) flag which restricts Telepresence from DNS resolving unneeded namespaces which might improve response time.

**Comment by thallgren** [comment]
@jckos , please close this issue or provide some feedback to our suggestions.

**Comment by jckos** [comment]
> You might also try the [--mapped-namespaces](https://www.getambassador.io/docs/telepresence/latest/howtos/large-clusters#limiting-at-connect) flag which restricts Telepresence from DNS resolving unneeded namespaces which might improve response time.

This resolved the issue (we have a lot of namespaces in the cluster). Thank You.
