### ISSUE TITLE
Microsoft recommendations to improve security and resilience in the traffic-manager 2.3.1 service

### ISSUE THREAD

**Issue by sairinraychoudhury** [telepresenceio/telepresence#3689]
Hi Everyone
Needed advice from community members. We have deployed traffic-manager 2.3.1 using helm in Microsoft Azure Kubernetes Service (AKS). Also during an assessment of our platform towards improved security & resilience angle received below recommendations from Microsoft experts to be implemented.
1. Containers sharing sensitive host namespaces should be avoided
2. Least privileged Linux capabilities should be enforced for containers
3. Privileged containers should be avoided
4. Usage of host networking and ports should be restricted.
5. Usage of pod HostPath volume mounts should be restricted to a known list to restrict node access from compromised containers
6. The root access inside the service container should be avoided.

We are not sure if above actions when implemented will have an impact on traffic-manager since we used default traffic-manager configs which are in helm chart for traffic-manager.

Could anyone from the community please help or guide us  on below queries?
1. Have you tried implementing custom configs apart from default configs provided?
2. Do you have a view of the impact by any means if we go ahead and implement this?
3. Are there any other general recommendation towards achieving this?

**Comment by thallgren** [comment]
@sairinraychoudhury why are you using version 2.3.1? It's very old.

Telepresence (the current version, 2.19.1) may be impacted by some of the recommendations. Let me go through them.

> 1. Containers sharing sensitive host namespaces should be avoided

Telepresence will not require any sharing of namespaces. You can run the traffic-manager and all agents in one single namespace if you wish.

> 2. Least privileged Linux capabilities should be enforced for containers

This is OK if you use services with symbolic target ports (e.g. "http" instead of "8080") , but Telepresence must install an init-container that requires NET_ADMIN capabilities when numeric target ports are used.

> 3. Privileged containers should be avoided

Same answer as for number 2.

> 4. Usage of host networking and ports should be restricted.

Depending on how hard the restrictions are, this might have an impact. It must be possible for a client to create a port-forward to the traffic-manager, and it must be possible for the Telepresence traffic-agent sidecars to communicate with the traffic-manager.

> 5. Usage of pod HostPath volume mounts should be restricted to a known list to restrict node access from compromised containers

Telepresence doesn't need HostPath volume mounts.

> 6. The root access inside the service container should be avoided.

Telepresence will not require root access from any of its containers.

I'll close this issue because it's a question, not a bug report or a feature request. Please use the #telepresence-oss channel on our [slack forum](https://slack.cncf.io) for further discussions.
