### ISSUE TITLE
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence98')"]' returned non-zero exit status 1

### ISSUE THREAD

**Issue by johackim** [telepresenceio/telepresence#380]
### What were you trying to do?

Just try to use Telepresence with minikube : 

```bash
telepresence --run-shell
```

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--run-shell']`
Version: `0.72`
Python version: `3.6.3 (default, Oct 24 2017, 14:48:20) 
[GCC 7.2.0]`
kubectl version: `Client Version: v1.8.4`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Linux arch 4.14.5-1-ARCH #1 SMP PREEMPT Sun Dec 10 14:50:30 UTC 2017 x86_64 GNU/Linux`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/usr/local/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/main.py", line 493, in go
    runner, remote_info, args, env, subprocesses, socks_port, ssh
  File "/usr/local/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/local.py", line 154, in run_local_command
    connect_sshuttle(runner, remote_info, args, subprocesses, env, ssh)
  File "/usr/local/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 225, in connect_sshuttle
    get_hellotelepresence()
  File "/usr/local/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/vpn.py", line 214, in get_hellotelepresence
    format(next(counter))
  File "/usr/local/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 95, in get_output
    result = str(check_output(*args, **kwargs).strip(), "utf-8")
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence98')"]' returned non-zero exit status 1.

```

Logs:

```
] Name or service not known
  33.2 TL | [134] Capturing: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence95')"],)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
  33.4 TL | [135] Capturing: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence96')"],)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
  33.6 TL | [136] Capturing: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence97')"],)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
  33.8 TL | [137] Capturing: (['python3', '-c', "import socket; socket.gethostbyname('hellotelepresence98')"],)...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known

```

**Comment by ark3** [comment]
Sorry about the crash. It looks like DNS is not getting captured by sshuttle or the proxy pod is failing to start correctly. Can you try running Telepresence against a remote cluster (quick and easy one available via [Kubernaut](https://github.com/datawire/kubernaut#quick-start))? 

Also, can you try the container method, which uses a different way of intercepting the network?`telepresence --docker-run --rm -it alpine sh`

**Comment by ston3o** [comment]
@ark3 

I have try with kubernaut and I have the same error.

And with `telepresence --docker-run --rm -it alpine sh` I have this error :

```
Traceback (most recent call last):
  File "/usr/local/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/cli.py", line 73, in call_f
    return f(*args, **kwargs)
  File "/usr/local/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/main.py", line 489, in go
    ssh,
  File "/usr/local/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/container.py", line 118, in run_docker_command
    TELEPRESENCE_LOCAL_IMAGE, "wait"
  File "/usr/local/share/telepresence/libexec/lib/python3.6/site-packages/telepresence/runner.py", line 84, in check_call
    raise CalledProcessError(retcode, args)
subprocess.CalledProcessError: Command '(['docker', 'run', '--network=container:telepresence-1513678792-5284364-9456', '--rm', 'datawire/telepresence-local:0.72', 'wait'],)' returned non-zero exit status 1.

```

Logs:

```
3678796-024839-9456" deleted
  26.7 75 | [INFO  tini (1)] Spawned child process 'python3' with pid '7'
  26.9 76 | [INFO  tini (1)] Spawned child process 'python3' with pid '7'
  27.0 75 |    0.0 TL | Telepresence launched at Tue Dec 19 10:19:58 2017
  27.0 75 |    0.0 TL |   ['/usr/bin/entrypoint.py', 'proxy', '{"port": 38543, "cidrs": ["10.96.0.0/12"], "expose_ports": []}']
  27.2 75 | Starting sshuttle proxy.
  27.4 75 | firewall manager: Starting firewall with Python version 3.6.1
  27.4 75 | firewall manager: ready method name nat.
  27.4 75 | IPv6 enabled: False
  27.4 75 | UDP enabled: False
  27.4 75 | DNS enabled: True
  27.4 75 | TCP redirector listening on ('127.0.0.1', 12300).
  27.4 75 | DNS listening on ('127.0.0.1', 12300).
  27.4 75 | Starting client with Python version 3.6.1
  27.4 75 | c : connecting to server...
  37.1 76 | Failed to connect to proxy in remote cluster.
  37.1 76 | [INFO  tini (1)] Main child exited normally (with status '1')
  37.4 TL | [76] exit 1.

```

**Comment by ston3o** [comment]
I have been able to run `telepresence --run-shell`. Its stay some bugs but it's works. Anyway thanks a lot for your work, telepresence is cool ;)

**Comment by ark3** [comment]
We don't test on Arch Linux, but I'm not sure why it wouldn't work. I would appreciate looking at a GitHub Gist of the full telepresence.log from the `--docker-run` attempt. Thank you!

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!

**Comment by OmerBilgin21** [comment]
I'm now facing the same issue described here.
I am also using Arch Linux, specifically Manjaro.
The error occurs both with my kubernetes pod and when running `telepresence --docker-run --rm -it alpine sh`

Telepresence version: 0.109
Docker version: 24.0.0
minikube version: 1.30.1
Manjaro version: 23.0.0

The terminal output looks like this: 
`
Traceback (most recent call last):
  File "/usr/bin/telepresence/telepresence/cli.py", line 135, in crash_reporting
    yield
  File "/usr/bin/telepresence/telepresence/main.py", line 81, in main
    user_process = launch(
                   ^^^^^^^
  File "/usr/bin/telepresence/telepresence/outbound/setup.py", line 157, in launch
    return run_docker_command(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/telepresence/telepresence/outbound/container.py", line 195, in run_docker_command
    runner.check_call(
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 458, in check_call
    self._run_command_sync(
  File "/usr/bin/telepresence/telepresence/runner/runner.py", line 437, in _run_command_sync
    raise CalledProcessError(
subprocess.CalledProcessError: Command '['docker', 'run', '--network=container:telepresence-1687264546-2591696-403654', '--rm', 'datawire/telepresence-local:0.109', 'wait']' returned non-zero exit status 1.
`

Last  few lines of the logfile:
`  10.1  21 | T: Your process exited with return code 99.
  10.2  24 | Connection to <> closed by remote host.
  10.2  21 | [INFO  tini (1)] Main child exited normally (with status '99')
  10.2 TEL | [24] Local SSH port forward: exit 255
  10.5 TEL | [21] Network container: exit 99
  31.3 TEL | [26] Running: sudo -n echo -n
  31.3 TEL | [26] ran in 0.04 secs.
  34.5 TEL | (proxy checking local liveness)
  34.6  12 | 2023-06-20T12:36:14+0000 [Poll#info] Checkpoint
  39.4  25 | Failed to connect to proxy in remote cluster.
  39.4  25 | [INFO  tini (1)] Main child exited normally (with status '1')
  39.5 TEL | [25] exit 1 in 31.43 secs.
`

from looking at the telepresence.log the issue seems like it is about the following:
`iptables: No chain/target/match by that name.`
This happens after: 
`iptables -t nat -A sshuttle-12300 -j REDIRECT --dest 0.0.0.0/0 -p tcp --to-ports 12300 -m ttl ! --ttl 42`

I tried clearing all the chains and restarting iptables.service, docker and minikube but it didn't help.

I'm new to these topics so any help would be appreciated.
