### ISSUE TITLE
inject-tcp method does not work on ubuntu 16.04

### ISSUE THREAD

**Issue by sameersbn** [telepresenceio/telepresence#423]
I followed the steps listed in https://github.com/kubeapps/dashboard/tree/2.0#running-in-development to setup a kubeapps development environment and I notice that telepresence would terminate when I make requests to the UI process (react app, running under telepresence) of kubeapps 

I'm using minikube v0.24.1 on a Ubuntu 16.04 machine for development. Attached is the log with the `--verbose` flag added to the telepresence command.

[telepresence.log](https://github.com/datawire/telepresence/files/1651250/telepresence.log)

Furthermore, if I instead use the `vpn-tcp` method (`telepresence --namespace kubeapps --method vpn-tcp --swap-deployment kubeapps-dashboard-ui --expose 3000:8080 --run yarn run start`) then it appears to be working fine. 

Any ideas on how to debug/fix the inject-tcp use case?

**Comment by ark3** [comment]
Thanks for the detailed bug report. 

Hmm. There are a couple of places this can go wrong. 

1. There is an incompatibility between inject-tcp and some servers in some network conditions due to a Telepresence proxy bug (#195).
2. There may be an interaction between how Telepresence uses torsocks and access to localhost, i.e. Minikube.

If this setup works correctly with a remote cluster but fails with Minikube, that would narrow the scope of possibilities.

**Comment by sameersbn** [comment]
> If this setup works correctly with a remote cluster but fails with Minikube, that would narrow the scope of possibilities.

With a GKE cluster, I see the same results.
Apparently it works on a MacOS workstation, but I haven't tried it.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
