### ISSUE TITLE
Discuss alternate UX for Telepresence

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#455]
The following Telepresence UX problems come up regularly.

1. Startup and shutdown take too long
2. Usage with alternatives (VPNs, file syncing) is difficult
3. Invocation (command line) is very complicated

## Problems

Let's consider how we can address these issues.

### Startup and shutdown take too long

Beyond the usual software performance techniques, we can make Telepresence start and stop faster by simply doing less on every invocation. At present, Telepresence enables all of its features on every invocation and must undo all of them on shutdown. Having a mechanism to allow usage of a subset of features could help immensely.

We can also mitigate this problem by making it easier to leave Telepresence running, e.g., by improving its stability. The fewer times you have to start and stop Telepresence, the less you experience startup and shutdown latency.

### Usage with alternatives is difficult

Some tools are partial alternatives to Telepresence, tools that solve a subset of the problems that Telepresence solves. For example, a quick web search for "VPN Kubernetes" yields several options for allowing local code to talk to your cluster. For access to volumes and secrets, there are file synchronization tools that can be helpful. However, these tools do not coexist well with Telepresence. Moreover, because it enables every feature on every invocation, Telepresence does not even coexist well with itself, at least when using the default vpn-tcp method.

Avoiding a clash between Telepresence features and other tools means not activating those conflicting features in the first place. Telepresence would benefit from being able to use a subset of its features.

### Invocation is very complicated

Launching Telepresence at the command line can be challenging to get right. There are many arguments and flags, and nearly all of them are optional. If we add more flags to allow selecting a subset of features as above, things become even more complicated. Once constructed, the correct command line is reusable to a point, but often needs to change depending on which project you are working on or which cluster you are using.

We can address this problem by allowing Telepresence to use persistent information where it makes sense instead of requiring everything on the command line every time. Telepresence can use information stored in the cluster (config maps or annotations), with the project (checked in to Git), and on the developer endpoint (your laptop). Going beyond persistent information, Telepresence could use persistent processes at both ends of the connection to manage invocation complexity. Persistent processes might help with performance too.

Once again we can mitigate this problem by making it easier to leave an invocation of Telepresence running for a long time. The fewer times you have to launch Telepresence, the less you experience invocation complexity.

## Solutions

Right now, the lifecycle of a Telepresence session begins with running the command, which enables all of Telepresence's features, and ends when the command quits. The user must specify on the command line everything that affects what Telepresence does, other than the current kubectl context. This approach is easy to understand and self-contained.

Solving the problems above may require a more complex Telepresence lifecycle. To summarize the approaches discussed above, we want to make it so you can:

1. Invoke Telepresence less often.
2. Activate only the features you want.
3. Not specify everything for every command.

Consider an alternate Telepresence UX that uses multiple (simple) command invocations to manipulate persistent state (data and running code on your laptop and in the cluster), enabling or disabling individual Telepresence features as desired.

### Aside: What does Telepresence enable?

- Connections from the cluster to the laptop/container
- Connections from the laptop/container to the cluster
- DNS names in the cluster visible to the laptop/container
- Pod filesystem accessible to the laptop/container
- Pod environment visible to the laptop/container

## Discussion

Let's discuss how Telepresence might work as a set of simple, composable commands. Good UX requires iteration and usage, so do not expect to get this right on our first try. Nevertheless, a bit of discussion can get us to a good starting point. A clear target can facilitate quick implementation and subsequent iteration.

How do you picture your ideal daily Telepresence workflow? What command(s) would you type? What would happen?

**Comment by ofpiyush** [comment]
## Central server

`telepresence init` could set the central server server up. The central server has the following responsibilities.

It can be interactive with initial setup questions and backed by a configmap. 

With this approach, one/two devs need to know all nitty gritty details of how things work and bulk of the users just need to know a simple set of commands for daily work.

### Configuration
Global configuration and sane defaults can be set on this server.

Things like services CIDR and `--also-proxy` for nodes CIDR on their platform can be kept in the central server. 

### State Management and recovery

It is my firm belief that the central server should be the one to manage deployment replacing etc.

I can't count the number of times one of our developers has lost connection/ just shut their lid to go out and ended up wrecking everything. 

Copy deployment (#407) helped lower these incidents, but there needs to be some recovery mechanism built in.

### Networking

I might be biased based on my work flow. The solution to me looks like 2 step. Use an always running VPN/VPN-like connection to connect. (Ref #413)

Probably run a full VPN server as part of the central server? Switch the VPN client when the context is switched?

### Environments

The central server can keep a cache of environment variables and forward them when necessary.

This means if you are not expecting traffic to come to you/have a FS mounted, there is no need to make a deployment on the cluster at all. The server can have an endpoint that gives this information to trusted clients.

## Deployment replacer

As stated above in cases where we don't need to, this container just should not be brought up.

Use very light weight containers (preferably scratch containers written in something like go?) to forward traffic from local and speed up time to deploy.

OpenVPN also allows one to keep certain ports always forwarded per client certificate.

So it could be as simple as just pointing the deployment-replacer as a reverse proxy to the central server.

## Local config

If we have a cluster wide setup, we probably don't need to keep a global local config, sane defaults can be configured centrally and each client gets to use that.

Each project(git root/directory?) however needs a dotfile or some file to store the defaults for that project. CLI flags should only be used to override the configuration in this dotfile.

## Commands
- `init` to set the central server up.
- `telepresence` can be a wrapper on top of `kubectl` like how `hub` is for `git`


PS: Running containers locally is not what I do, I am not sure how that workflow would/should work. If something I said breaks their workflow, it is because I am unaware of the issues there.

**Comment by ofpiyush** [comment]
I didn't write about it here as it is already covered in #407 we use that @verloop 👍

**Comment by DandyDeveloper** [comment]
Just from personal experience. One use case we have here is a simple dev machine that deploys the tcp-vpn enabling our developers to access the numerous microservices sat on other Kubernetes clusters in order to test different scenarios. 

For us, this only requires us running Telepesence silently in the background. We don't actually need the terminal opened through Telepresence. I recommended having some form of `--quiet` flag to support this, but a central server might be fit for purpose. 

The idea of having the CLI init and silently run as a process in the same way `minikube` does would be pretty ideal. 

Having an environment defined through a `.telepresence` configuration file would be great. 

I'll append any other thought I have to this post as I toy more with the options available on Telepresence.

**Comment by donnyyung** [comment]
A lot of these suggestions have been integrated into Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please open issues if you can think of future features or improvements that would make the UX better.
