### ISSUE TITLE
Explore running DNS locally (vpn-tcp)

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#559]
When using the vpn-tcp method, Telepresence forwards all DNS requests to our server running in the cluster. This characteristic of vpn-tcp is one way in which it is very intrusive. Let's explore running our DNS server on the host instead. This would allow Telepresence to delegate non-cluster lookups to a local resolver, making them much more likely to behave as they would without vpn-tcp. As a side effect, it would be easier to avoid DNS loops when running a local cluster, such as Minikube or Kubernetes for Docker.

**Comment by rkr-kununu** [comment]
I've got a related use-case:  My company has their local dns server which has some custom domains.  However, when I start telepresence, the sshuttle forwards all my dns requests into the k8s cluster (which won't resolve the services running on my local network).

But shuttle now provides `--auto-host` and `--hostwatch` which are designed to solve this use case (the host's resolve.conf is _not_ modified).  Is this something that can be integrated into Telepresence?

Source: https://sshuttle.readthedocs.io/en/stable/manpage.html

**Comment by RXminuS** [comment]
Where are we on this @ark3, would @rkr-kununu 's suggestion work? We've run into the same problem and would love to either post a bounty to fix this if there is a reasonable idea for a solution :-)

**Comment by richarddli** [comment]
@RXminuS feel free to contact us at hello@datawire.io if you want us to do specific development. A number of key features in Telepresence were sponsored by other companies, and we are grateful for their support!

**Comment by rkr-kununu** [comment]
@RXminuS I rutted around the source code for telepresence and also sshuttle.  Unfortunately, ```--auto-host``` and ```--hostwatch``` will _not_ work.  Basically, an sshuttle connection created with these options will cause sshuttle to periodically run netstat (every 20-30 seconds)... then any open connections that happen _at that time_ are resolved and updated in the clients /etc/hosts file.

This means you have a chicken-and-egg problem:  You need the ip address, so you can establish a TCP connection, so that netstat finds the ip address and resolves the name.

At the moment, I think integration with [teleproxy](https://github.com/datawire/teleproxy/issues/3) seems to be the most interesting option.

**Comment by dikey94** [comment]
any progress on this? thanks
