### ISSUE TITLE
localhost does not reach the pod

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#621]
As [described in the documentation](https://www.telepresence.io/reference/limitations#localhost-and-the-pod), connecting to localhost reaches your machine (or your container), not the rest of the pod. The documented workaround is more easily done by using `$TELEPRESENCE_POD`, which lets you avoid having to use the downward API or mess with the deployment.

Some sort of local-port-proxy feature might be less intrusive. You'd have to tell Telepresence to proxy specific ports on localhost, but you wouldn't have to change your code. And something similar could work in the other direction too, allowing other containers in the pod to talk to your machine.

**Comment by madmod** [comment]
I think that the most common case, and the least surprising default would be to proxy all ports to the proxy, so that the local container behaves as if it were running in the cluster. Then a flag could be added to proxy ports from the local container to the local host if needed.

Also the proxy must preserve the exact IP requested by the caller. E.g. `curl 127.0.0.1`, `curl 127.0.0.123`, `curl [::1]`, and `curl [::123]` are not equivalent and should all be proxied. A sidecar should be able to listen to only ipv6 or `127.0.0.123` for example. If the request IP is not preserved exactly then there may be subtle bugs which only manifest when not running with telepresence, caused by client programs listening on `127.0.0.1` instead of `localhost` (Which resolves to all of these example IPs.) or by only listening for IPv4/6.
