### ISSUE TITLE
Telepresence should forward localhost ports to sidecar pods

### ISSUE THREAD

**Issue by ark3** [telepresenceio/telepresence#728]
- [ ] Figure out which ports to forward from the deployment (if possible)
- [ ] Offer a command line flag to add ports
- [ ] Use SSH port forwarding to get the job done

**Comment by nhartner** [comment]
Is there a workaround to connect to a sidecar port from the host machine running telepresence?

**Comment by nhartner** [comment]
More specifically, I'm using Telepresence with Intellij to swap out a deployment for a Java app. Everything works great except I haven't found a way to have the Java process in intellij connect to the sidecar (a cloud sql proxy). I tried connecting to the sidecar using the podIP instead of localhost but that didn't work, connection refused.

**Comment by nhartner** [comment]
The following works as a one-liner to start telepresence and then create the port-forward to the sidecar: 
```telepresence --swap-deployment my-service <<< 'kubectl port-forward $TELEPRESENCE_POD 5432'```
