### ISSUE TITLE
telepresence crashes if bashrc got prompt_git functions

### ISSUE THREAD

**Issue by dfang** [telepresenceio/telepresence#751]
```
prompt_git() {
.....
}

```
in my bashrc, i have to remove this, otherwise crash.

aliases work in telepresence --run-shell, but all functions are undefined

**Comment by ark3** [comment]
The Telepresence `--run-shell` setup goes through a lot of effort to avoid having the shell prompt crash under the inject-tcp method (by avoiding things like `kubectl` in the prompt command). It's probably more aggressive than it needs to be for the vpn-tcp method. In any case, it looks the efforts are insufficient for your prompt. What is your shell setup? What crash do you get from Telepresence? Thanks for your help chasing this down.

Also, you can try to work around this by using `--run bash` instead of `--run-shell`, though you may run into other issues then.
