### ISSUE TITLE
Brew install invalid SHA telepresence 0.92

### ISSUE THREAD

**Issue by AlexandreRoba** [telepresenceio/telepresence#754]
Dear All, I tried to install the latest version of telepresence 0.92 but I'm getting a SHA256 mistmatch:
```bash
brew install socat datawire/blackbird/telepresence
Warning: socat 1.7.3.2_2 is already installed and up-to-date
To reinstall 1.7.3.2_2, run `brew reinstall socat`
==> Installing telepresence from datawire/blackbird
==> Downloading https://github.com/telepresenceio/telepresence/archive/0.92.tar.gz
==> Downloading from https://codeload.github.com/telepresenceio/telepresence/tar.gz/0.92
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: c93bfe7e7591aa24b241d13effab6cf0fddbe66e139a75beffb25fa9971cd50b
Actual: 3ad4978333bbf69dc6e2f394054e43925e0025f3ff55b0480b5d5a3b18d9046c
Archive: /Users/aroba/Library/Caches/Homebrew/telepresence--0.92.tar.gz
To retry an incomplete download, remove the file above.
```

i tried to clean cash and remove any previous version but still

**Comment by thomaspheiffer** [comment]
I am also getting this SHA256 mismatch when trying to `brew upgrade telepresence` to 0.92.

**Comment by akath19** [comment]
I'm also getting the same SHA256 mismatch (with the same SHA256 hashes) on MacOS 10.13.6

**Comment by ark3** [comment]
It seems that the contents of the GitHub URL, in this case `https://github.com/telepresenceio/telepresence/archive/0.92.tar.gz`, change in some way after we commit to the master branch. This makes no sense to me. Does anyone have any ideas why this might be happening?

This should be fixed by [this commit](https://github.com/datawire/homebrew-blackbird/commit/bc33b408b351617edb9965818badd46991705f33).

**Comment by akath19** [comment]
@ark3 , it's working perfectly now, thanks!

**Comment by ark3** [comment]
I believe #768 will avoid this problem going forward. Closing.
