### ISSUE TITLE
Document universe repo stuff on Ubuntu 18.04

### ISSUE THREAD

**Issue by motek80** [telepresenceio/telepresence#822]
Having a clean Ubuntu 18.04 machine.

Calling 
`apt install --no-install-recommends telepresence`

Getting:

> Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 telepresence : Depends: torsocks but it is not installable
                Depends: sshfs but it is not installable
E: Unable to correct problems, you have held broken packages.

It looks like packages 'torsocks' and 'sshfs' are not available for some reason. Should I get them from some other place?

**Comment by ark3** [comment]
They are available on the official repositories: [torsocks](https://packages.ubuntu.com/bionic/torsocks) and [sshfs](https://packages.ubuntu.com/bionic/sshfs). What happens if you try to install them directly (`apt install torsocks sshfs`)? Perhaps apt will tell you why they are not installable. You can also try downloading them directly from those links and installing using something like `dpkg -i`.

**Comment by motek80** [comment]
https://askubuntu.com/questions/1075605/sshfs-has-no-installation-candidate

> The sshfs package has been relocated to the universe repository:
**apt-add-repository universe**

**Comment by ark3** [comment]
Re-opening issue to document `apt-add-repository universe` as being possibly needed.
