### ISSUE TITLE
Dangling pods, deployments, left overs...

### ISSUE THREAD

**Issue by agolomoodysaada** [telepresenceio/telepresence#824]
Telepresence works great for our team but it seems to leak deployments, services, over several days. There doesn't seem to be an automatic cleanup that happens due to slow network connections. Who takes care of cleaning up telepresence resources? The pod itself? The client? What if the client loses internet connection? Is there a flag we need to set for automatic cleanup?

Because of this, we end up with deployment and service leaks for telepresence sessions that ended several days ago. This is with v0.92.

**Comment by hrickards** [comment]
Bump. Any update?

**Comment by ark3** [comment]
The primary tracking issue for this is #260. The command line client is responsible for cleanup. This means that if the user closes the laptop to go to a meeting before ending the session, or switches networks before ending the session, or bangs on Ctrl-C too many times, cleanup doesn't happen correctly. Those are all reasonable things for the user to do, so this is definitely a Telepresence bug that needs to be fixed. We have sketched out an approach in #260 but have not had time to move things forward. PRs would be appreciated!

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2, since you can use the `telepresence uninstall` command to clean up agents that have been applied to workloads, as well as the traffic-manager itself. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
