### ISSUE TITLE
Providing metadata to new deployment

### ISSUE THREAD

**Issue by motek80** [telepresenceio/telepresence#861]
Is it possible to provide metadata for "new deployment"?

For example, run pod as a Job or/and run it under specific ServiceAccount?

**Comment by ark3** [comment]
Telepresence does not have that feature at present. You will have to [launch the deployment manually](https://www.telepresence.io/reference/connecting#running-telepresence-manually).

**Comment by number101010** [comment]
I would like this same feature when using the `--docker-run` mode.   Specifically I would like to provide a service account for the new pod.  This would allow for easier development of applications that interact with the Kubernetes API.

I've recently updated https://github.com/number101010/go-kubernetes-vscode-dev to use the new `--docker-run` feature and would love to be able to set the service account of the new pod.  Otherwise I will have to give the default serviceaccount permissions against the API.

**Comment by ark3** [comment]
@number101010 You can use the existing deployment operation with the container method. I suggest adding a

    kubectl run ... dep-name ...

command to the [launcher script](https://github.com/number101010/go-kubernetes-vscode-dev/blob/master/.debug/debug.sh#L13) similar to [the one from Tel](https://github.com/telepresenceio/telepresence/blob/0.96/telepresence/proxy/deployment.py#L73). That would give you the opportunity to include `--serviceaccount` and any other options directly. You could also pass a manifest to `kubectl apply` if you want complete configurability. [The documentation](https://www.telepresence.io/reference/connecting#running-telepresence-manually) has an example. 

In either case, you then pass `--deployment dep-name` to Telepresence so that it will use your deployment.

That's a cool use of Telepresence you've got there. Please let me know if you have any other questions.
