### ISSUE TITLE
Failure to launch user process when the environment is too big (too many services)

### ISSUE THREAD

**Issue by argel** [telepresenceio/telepresence#900]
Hi, I’m trying to follow the getting started guide and in the step 
`telepresence --deployment myserver --expose 8080 --run-shell` 
I get the following message 
`Failed to launch your command: [Errno 7] Argument list too long: 'bash' `

On the slack channel the people says that could be that there are too many kubernetes services running so the environment is too big. 

I've attached the log to see if someone can help me to solve this issue.

[telepresence.log](https://github.com/telepresenceio/telepresence/files/2764249/telepresence.log)

The cluster namespace that throw the error has about 500 services running, if I use another namespace with little services running I can complete the getting started guide without any issues.

Thank you for your help

**Comment by ark3** [comment]
Out of curiosity, do you use the service env vars? E.g.,

```
$ telepresence --run env | grep ECHO
ECHO_PORT_80_TCP_ADDR=10.99.251.85
ECHO_PORT_80_TCP_PROTO=tcp
ECHO_SERVICE_HOST=10.99.251.85
ECHO_PORT=tcp://10.99.251.85:80
ECHO_SERVICE_PORT_PROXIED=80
ECHO_PORT_80_TCP_PORT=80
ECHO_PORT_80_TCP=tcp://10.99.251.85:80
ECHO_SERVICE_PORT=80
```

Telepresence ought to notice that the environment is too big, warn that it's cutting down the environment, and launch your process with that reduced environment. But I'm not sure what would be the right way to cut down the environment. Thoughts?

**Comment by argel** [comment]
I'm only using the variables to get the curren service host and port (which is kind of useless in my environment) the discovery of services is mostly through DNS. In my personal case cutting down most of the "docker link" kind of env var would be no problem I guess

**Comment by hudelgado** [comment]
Hello, I also run into this problem because of the high number of services in a cluster and created a small patch to allow the use of the  `--env-file` argument in the `--docker-run` parameter.
This way if the parameter is present in the docker run command it will use it, otherwise it will use the regular `--env VAR2=value2` assignment for the environment variables.

The change [can be checked here](https://github.com/hudelgado/telepresence/blob/fix/issue_900_env_vars_too_big_to_start_docker/telepresence/outbound/container.py#L232)


Is this strategy ok, and is something that would worth add?
I won't mind in adjusting it according to the feedback I receive.

Thanks and congrats for the great work in this tool.

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
