### ISSUE TITLE
T: Error: Namespace 'default' does not exist

### ISSUE THREAD

**Issue by xiuxiu** [telepresenceio/telepresence#914]
Hi All,

I am development using Mac OS X. At first, Telepresence works well with my Docker Desktop Kubernetes. And then I try to close local Kubernetes and connect to remote kubernetes cluster with telepresence.

Unfortunately, when I start Telepresnce with Docker Desktop Kubernetes closed, I got the following error message.

>telepresence
T: Error: Namespace 'default' does not exist

Any idea?

Regards
Rock

**Comment by MaurGi** [comment]
I work in an heterogeneous environment with different versions of servers and kubectl. I have an alias that will chose the right version of the kubectl depending on the server: [K](https://github.com/jakepearson/k )

Can I configure telepresence to use my K alias rather than the default /snap/bin/kubectl ?

**Comment by ark3** [comment]
@MaurGi Not at the moment, at least not in the form of a "run _this_ instead of `kubectl`/`oc`" option. 

Telepresence runs whatever `kubectl` is in your path. As a workaround, you could name your script `kubectl` and place it earliest in your shell path, ahead of any other `kubectl`. Another possibility would be to write a wrapper script for Telepresence that sets the shell path before calling the real Telepresence.

Cool script, by the way. Thank you for sharing that.

**Comment by MaurGi** [comment]
Yeah if we could configure an environment variable to use instead of kubectl, something like 

`export KUBECTL_CMD="k"`

before calling telepresence, that would work - 

Thank you -

**Comment by yelhouti** [comment]
I'm having the same problem, and I think it's due to missing permission "list" "namespace".
I don't think I should need this to target the namespace I want, and maybe something in the code is doing a check that requires high privileges making telepresence fail

**Comment by kilianc** [comment]
This happens to me when I use `telepresence --run` and I `^C` stopping the command. Internet on my machine stops working

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
