### ISSUE TITLE
"too many open files" from kubectl logs

### ISSUE THREAD

**Issue by nicolasbelanger** [telepresenceio/telepresence#916]
### What were you trying to do?

Simply trying `telepresence --run-shell`

### What did you expect to happen?

Work all the time :)

### What happened instead?

Crash (randomly for lack of better explanation) at logs tail step with too many open files.

Complete telepresence.log here: https://gist.github.com/nicolasbelanger/b699a5b2f83d5b85cbde5db95470bb5b

### Automatically included information

Command line: `['/usr/local/bin/telepresence', '--run-shell']`
Version: `0.97`
Python version: `3.7.2 (default, Jan 13 2019, 12:50:01) 
[Clang 10.0.0 (clang-1000.11.45.5)]`
kubectl version: `Client Version: v1.10.7 // Server Version: v1.11.6-gke.0`
oc version: `(error: [Errno 2] No such file or directory: 'oc': 'oc')`
OS: `Darwin MacBook-Pro-8.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64`

```
Background process (kubectl logs) exited with return code 0. Command was:
  kubectl --context ***** --namespace nicolas logs -f telepresence-1549031264-2952871-31200-5745899d56-wfddp --container telepresence-1549031264-2952871-31200 --tail=10

Recent output was:
  failed to create fsnotify watcher: too many open files
```

Logs:

```
hamerica-northeast1_teocity-kubernetes-cluster --namespace nicolas logs -f telepresence-1549031264-2952871-31200-5745899d56-wfddp --container telepresence-1549031264-2952871-31200 --tail=10
   3.6 TEL | [17] Launching kubectl port-forward: kubectl --context ***** --namespace nicolas port-forward telepresence-1549031264-2952871-31200-5745899d56-wfddp 50624:8022
   3.6 TEL | [18] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 50624 telepresence@127.0.0.1 /bin/true
   3.6 TEL | [18] exit 255 in 0.02 secs.
   3.8  16 | failed to create fsnotify watcher: too many open files
   3.8 TEL | [16] exit 0
   3.9 TEL | [19] Running: ssh -F /dev/null -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -q -p 50624 telepresence@127.0.0.1 /bin/true
   3.9 TEL | [19] exit 255 in 0.02 secs.
   4.0  17 | Forwarding from 127.0.0.1:50624 -> 8022
   4.0  17 | Forwarding from [::1]:50624 -> 8022

```

**Comment by ark3** [comment]
I think you're experiencing kubernetes/kubernetes#64315. The issue appears randomly because it depends on which node your Telepresence deployment happens to be scheduled on; if you hit one whose file descriptors have been exhausted, you would see this failure. The issue comments don't suggest any workarounds, though I suppose removing the failing nodes and adding new ones to replace them would get things running again. Yes, that's a very intrusive workaround. Telepresence itself should not be causing this issue, as the proxy container generates log output every thirty seconds at a minimum. Are you running `kubectl logs` on containers that do not generate output?

As for getting Telepresence working for you, the core problem is #598. Having the proxy container logs (via `kubectl logs`) in the Telepresence log file is very handy for debugging, but making it optional would certainly help in some cases, like this one. I'll try to fix #598 for the next release.
