### ISSUE TITLE
ctrl+c is probably not the best choice of exit telepresence session

### ISSUE THREAD

**Issue by sokoow** [telepresenceio/telepresence#936]
I discovered this upon doing tests for https://github.com/telepresenceio/telepresence/issues/935 , and this is probably related to https://github.com/telepresenceio/telepresence/issues/337

So, when my command at https://github.com/telepresenceio/telepresence/issues/935 hangs in container mode, I'm  tempted to hit ctrl+c and stop it, problem is that this also stops telepresence:

```
T: Keyboard interrupt (Ctrl-C/Ctrl-Break) pressed
T: Exit cleanup in progress
T: Cleaning up Deployment telepresence-1551079420-434663-6647
```
I think it's just not a good combo for killing telepresence, it's rather annoying. If it's set at telepresence level, can this be changed ?

**Comment by ark3** [comment]
When you hit Ctrl-C, the terminal sends SIGINT to your process. I think the shell passes that along to all the foreground processes. That means Docker will see it, but so will Telepresence (and many of the subprocesses it has launched, depending on whether Tel has detached them). We may be able to construct a heuristic to make Telepresence ignore Ctrl-C some of the time (but not all the time!). It's complicated...

**Comment by sokoow** [comment]
I think I'd jut change the combination and ignore SIGINT

**Comment by LukeShu** [comment]
telepresence isn't handling a keyboard combination.  It's assuming that whenever it receives SIGINT, that was caused by Ctrl-C.  Try `kill -INT <PID_OF_TELEPRESENCE>`; it will print the same message even though it wasn't caused by Ctrl-C.  This assumption is kinda baked in to Python, actually, when the Python interpreter receives SIGINT, it raises `KeyboardInterrupt`.

Now, there is an ioctl to change what keystroke causes the terminal to send SIGINT (or disable having a keystroke send SIGINT).  We could do that, but it would cause a bunch of other headaches.

Now, something else we could do is to have Telepresence "get out of the way" and let the inferior process receive the signal directly, like a shell does:

```console
$ # add visibility in to Bash receiving SIGINT:
$ trap 'echo received sigint' SIGINT

$ # "Normally," bash receives SIGINT when you press Ctrl-C:
$ ^Creceived sigint
$

$ # But when we run a another foreground process, Bash "gets out of the way", and the signal goes straight to the foreground process:
$ sleep 9999
^C
$ 
```

**Comment by donnyyung** [comment]
I believe this is no longer an issue in Telepresence 2. Here are the docs on how to install Telepresence (https://www.telepresence.io/docs/latest/install/), please re-open if you still see this issue in our latest version!
