### ISSUE TITLE
VPN connection issue and crash with vpn-tcp method

### ISSUE THREAD

**Issue by alexloiko** [telepresenceio/telepresence#982]
Hi, I have an issue with VPN connection from macOS Mojave using vpn-tcp method.

I try to use telepresence in combine with Intellij Idea and java Spring Boot application for local debug.
Suppose I have deployed service `api`, `postgres` and others inside my kubernetes cluster.

After run of
`telepresence --swap-deployment api --env-json api_env.json`
it seems that all is ok: app says it lunched and I can resolve by `host kubernetes`.

First time use all will be ok with telepresence, I used is for several times.
But one day I was not able to connect to cluster (e.g. db), so I can receive requests, but not send.
But last time after around 1 minute from start, the connection became lost and `host kubernetes` returns not found. And there were logs that connection crashed at all. 

Also application exits with error and logs:
https://gist.github.com/tryelse/705edff7bcbb8a812f31643748529791

p.s
version 0.98, installed via brew

Tried inject-tcp not working at all for me.
I usually use the vpn with Tunnelblick to my another private network, but during telepresence use it is disabled or closed. Possibly they have some conflict.
First time use all will be ok with telepresence, but after some time I get such troubles and its a pity.
Maybe it is connected with issue https://github.com/telepresenceio/telepresence/issues/958

If you have any ideas or maybe it is a bug - please give some advice.
Thanks.

**Comment by ark3** [comment]
The vpn-tcp method is incompatible with other VPNs, as you have already noted. Unfortunately Telepresence is not smart enough to detect the conflict; instead of reporting an error, it fails in strange ways. Please turn off other VPNs when using Telepresence.

Your logfile is reminiscent of others I have seen and not solved. It looks like things are okay until the 970 second mark (about 16 minutes). Then there's an access to 10.103.124.250:8079 (maybe auth?). About 15 seconds later, something tries connecting repeatedly to 10.103.124.250:80 (same IP, different port) very quickly. This uses up all available connections and causes Telepresence to crash. I'm really not sure why this would happen; as I said, I've seen this before but have not (yet!) found a solution.

**Comment by tryelse** [comment]
@ark3 Thanks for the reply
The thing that there is no any error in logs connected with vpn. So I confused what is bad in configuration or environment.
Maybe as a feature there can be ping of some internal ip or service, e.g. kubernetes, to check we are still inside network.
